import type {CaptureMetadata} from '../../../adapters/capture-metadata.mjs'
import type {ForgetRecordSummary} from '../../../adapters/forget-review.mjs'
import type {ForgetWorkflowSnapshot} from '../../../adapters/forget-result.mjs'
export interface MemoryCapture {readonly statement:string;readonly attributed_to:string}
export interface Presentation { readonly operation: Readonly<Record<string,unknown>>; readonly operation_digest:string; readonly approval_expiry:string; readonly canonical_operation:string; readonly review_challenge:Readonly<Record<string,unknown>>; readonly rows: readonly {key:string;label:string;exact:string}[]; readonly capture_metadata:CaptureMetadata|null; readonly forget_review:(ForgetRecordSummary & {readonly canonical_sha256:string})|null; readonly memory_review:(MemoryCapture & {readonly capture_sha256:string})|null }
export interface Capabilities {readonly version:1;readonly source_commit:string;readonly runtime_pid:number;readonly release_digest:string;readonly unavailable_capabilities:readonly string[];readonly phase:'disposable-preview';readonly qualification:'PENDING'}
export interface ApprovalActionResult {readonly phase:string;readonly operation:Readonly<Record<string,unknown>>|null;readonly memory_capture:MemoryCapture|null;readonly operation_digest:string|null;readonly approval:string;readonly save:string;readonly saved:boolean|null;readonly record:Readonly<Record<string,unknown>>|null;readonly receipt:Readonly<Record<string,unknown>>|null;readonly receipt_digest:string|null;readonly citation:Readonly<Record<string,unknown>>|null;readonly citation_status:string;readonly index:{readonly status:string;readonly indexed:boolean|null;readonly searchable:boolean|null};readonly authority_settlement:string|null;readonly reconciliation_required:boolean;readonly error_code:string|null;readonly read_error_code:string|null}
export type ApprovalAction=(presentation:Presentation,options:{signal:AbortSignal})=>Promise<ApprovalActionResult>
export type LogoutResult={readonly ok:true;readonly status:'LOGGED_OUT'}|{readonly ok:false;readonly error_code:string;readonly reason:string}
export type ForgetAction=(presentation:Presentation,options:{signal:AbortSignal})=>Promise<ForgetWorkflowSnapshot>
export interface OwnerState {readonly forget_action_result:ForgetWorkflowSnapshot|null;readonly logout_status:'idle'|'pending'|'confirmed'|'unknown'|'refused'|'unavailable';readonly logout_error_code:string|null;readonly phase:string;readonly owner:{owner_id:string;expiry:string}|null;readonly owner_id:string;readonly presentation:Presentation|null;readonly operation_available:boolean;readonly login_kinds:readonly string[];readonly fixture:boolean;readonly expired:boolean;readonly reason:string;readonly error_code:string|null;readonly capabilities:Capabilities|null;readonly capability_status:string;readonly authority_available:boolean;readonly approval_action_available:boolean;readonly approval_action_pending:boolean;readonly approval_action_result:ApprovalActionResult|null}
export interface Binding {authority:Record<string,(input:unknown,options?:{signal?:AbortSignal})=>Promise<unknown>>; contracts:{validateContract(name:string,value:unknown):unknown;validateApprovalTemplate?(value:unknown):unknown;parseStrictJson?(text:string,options?:{maxBytes?:number;maxDepth?:number}):unknown;canonicalJson(value:unknown):string;operationDigest(value:unknown):string|Promise<string>};owner_id?:string;loginKinds?:readonly string[];approvalKind?:string;fixture?:boolean;requiresCapabilities?:boolean;passkeyProfile?:{profile:'https'|'localhost-pilot-v1';origin:string;rp_id:string};ownerSigner?:(input:unknown)=>Promise<unknown>;passkeySigner?:(input:unknown)=>Promise<unknown>;operation?:unknown;memoryCapture?:MemoryCapture;captureMetadata?:CaptureMetadata;recordSummary?:ForgetRecordSummary}
export interface Controller {getSnapshot():OwnerState;subscribe(listener:()=>void):()=>void;connect(binding:Binding):void;setCapabilities(value:unknown):void;capabilitiesUnavailable():void;setOwnerId(owner_id:string):void;setOperation(proposal:unknown,options?:{memoryCapture?:MemoryCapture;captureMetadata?:CaptureMetadata;recordSummary?:ForgetRecordSummary}):void;login(kind?:string):Promise<unknown>;prepare():Promise<unknown>;approve():Promise<unknown>;setApprovalAction(handler:ApprovalAction|null):void;setForgetAction(handler:ForgetAction|null):void;submitApproval():Promise<unknown>;decline():Promise<unknown>;logout():Promise<LogoutResult>;disconnect():Promise<LogoutResult>;dispose():void}
export function createPrimeOwnerController(options?:{now?:()=>number;schedule?:typeof setTimeout;unschedule?:typeof clearTimeout}):Controller
export function createHttpAuthority(fetcher?:typeof fetch,contracts?:Binding['contracts']):Binding['authority']
export function readHttpCapabilities(fetcher?:typeof fetch,contracts?:Binding['contracts'],signal?:AbortSignal):Promise<Capabilities>
export function validateCapabilities(value:unknown):Capabilities
export const CAPABILITY_LABELS:Readonly<Record<string,string>>
