#!/usr/bin/env node
/**
 * install-hooks.mjs — plan section 5 row 11: THE HOOK IS INSTALLED BY A SCRIPT, NOT BY HAND.
 *
 * A hook that only exists in one person's `.git/hooks` is a convention, not a guarantee: a fresh clone, a second
 * checkout and a lane on another machine all silently lack it, and the commits they make carry no provenance while
 * looking exactly like the ones that do. So the hook is a VERSIONED FILE in the repository
 * (`scripts/aukora/hooks/prepare-commit-msg.mjs`) and this script writes the shim that calls it.
 *
 * IT IS IDEMPOTENT. Running it twice is not an error, a second shim or a changed file: the shim is compared byte for
 * byte and reported as already-installed.
 *
 * IT REFUSES A FOREIGN HOOK BY NAME rather than overwriting one. Somebody else's `prepare-commit-msg` may be doing
 * work nobody wrote down, and clobbering it to install provenance would trade a known feature for an unknown loss.
 * `--force` exists for the case where a person has read the file and decided.
 *
 * BOTH PATHS IN THE SHIM ARE ABSOLUTE, and that is not tidiness: hooks run under whatever environment git was
 * invoked with, and a lane that commits from a clean shell (`env -i`) has no `node` on PATH — the shim would exit
 * 127 and the commit would fail for a reason that has nothing to do with its message. The interpreter is the one
 * running this installer, and the hook path is resolved here, once.
 */
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { spawnSync } from 'node:child_process'
import { dirname, isAbsolute, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

export const HOOK_VERSION = 'aukora-hook-v1'
export const HOOK_NAME = 'prepare-commit-msg'
const HERE = dirname(fileURLToPath(import.meta.url))

export class InstallRefusal extends Error {
  constructor(name, message, code = 2) { super(message); this.name = name; this.code = code }
}

function git(repo, args) {
  const r = spawnSync('git', ['-C', repo, ...args], { encoding: 'utf8' })
  return { rc: r.status, out: String(r.stdout ?? '').trim(), err: String(r.stderr ?? '').trim() }
}

/** The prose of the shim, exported so the court can assert what is in it without running an install. */
export function shimFor({ nodePath, hookPath }) {
  return `#!/bin/sh
# GENERATED BY scripts/aukora/install-hooks.mjs — ${HOOK_VERSION} — DO NOT EDIT BY HAND.
# The logic lives in the repository at ${hookPath}; this file only calls it. Both paths are absolute because a hook
# runs under whatever environment git had, and a clean shell has no node on PATH.
exec ${nodePath} ${hookPath} "$@"
`
}

/** Install into `repo`. Returns { action, path, pathWas }. Throws a named refusal rather than clobbering. */
export function installHook({ repo = '.', force = false, nodePath = process.execPath, hookScript = join(HERE, 'hooks', `${HOOK_NAME}.mjs`) } = {}) {
  const resolvedRepo = resolve(repo)
  const inside = git(resolvedRepo, ['rev-parse', '--is-inside-work-tree'])
  if (inside.rc !== 0 || inside.out !== 'true') {
    throw new InstallRefusal('not-a-work-tree', `${resolvedRepo} is not inside a git work tree, so there are no hooks to install`)
  }
  // THE GIT DIR IS ASKED FOR ABSOLUTELY. MEASURED in this repository's own bisect tool: `--git-dir` answers a
  // RELATIVE path, and joining onto it searched the wrong directory — the same mistake here would install the shim
  // somewhere real and leave the hook that git actually runs untouched, which is a silent success.
  const answered = git(resolvedRepo, ['rev-parse', '--absolute-git-dir']).out
  if (answered === '') throw new InstallRefusal('git-dir-unreadable', `git could not say where the git dir of ${resolvedRepo} is`)
  const gitDir = isAbsolute(answered) ? answered : join(resolvedRepo, answered)
  const hooksDir = join(gitDir, 'hooks')
  const target = join(hooksDir, HOOK_NAME)
  const wanted = shimFor({ nodePath, hookPath: hookScript })

  if (existsSync(target)) {
    const existing = readFileSync(target, 'utf8')
    if (existing === wanted) return { action: 'already-installed', path: target, repo: resolvedRepo }
    if (!existing.includes(`GENERATED BY scripts/aukora/install-hooks.mjs`) && !force) {
      throw new InstallRefusal('hook-foreign', `${target} exists and was not written by this installer, so it has NOT been replaced: read it, then pass --force if you mean to lose it`)
    }
  }
  mkdirSync(hooksDir, { recursive: true })
  writeFileSync(target, wanted)
  chmodSync(target, 0o755)
  return { action: existsSync(target) ? 'installed' : 'installed', path: target, repo: resolvedRepo }
}

// ── CLI — AND ONLY WHEN THIS FILE IS THE ENTRY POINT ─────────────────────────────────────────────────────
async function cli() {
  const argv = process.argv.slice(2)
  const value = (flag) => { const i = argv.indexOf(flag); return i === -1 ? null : argv[i + 1] ?? null }
  const flag = (name) => argv.includes(name)
  try {
    const result = installHook({ repo: value('--repo') ?? '.', force: flag('--force') })
    process.stdout.write(flag('--json')
      ? `${JSON.stringify(result)}\n`
      : `${result.action}: ${result.path}\n`)
    process.exit(0)
  } catch (error) {
    if (error instanceof InstallRefusal) {
      process.stderr.write(`REFUSED: ${error.name}: ${error.message}\n`)
      process.exit(error.code)
    }
    throw error
  }
}

if (process.argv[1] !== undefined && pathToFileURL(process.argv[1]).href === import.meta.url) await cli()
