#!/usr/bin/env node
/**
 * THE DIAMOND COLD CONSUMER, RUN FROM A LITERAL EMPTY DIRECTORY, AGAINST A REAL EXPORT.
 *
 *   node tests/kira-diamond-cold.test.mjs            # every arm
 *   node tests/kira-diamond-cold.test.mjs --mutate   # every arm again, its invariant broken
 *
 * WHAT THIS COURT PROVES. `vendor/kira-export/scripts/verify-kira-evidence.py` — the frozen
 * Diamond consumer vendored at upstream pin 7400473825c5af4c17657604bf3d9c3c749ff1a1, whose own
 * docstring says "The consumer must run from an EMPTY directory. Its own package may be reached by
 * an explicit `--package-root`" — is executed with its process cwd set to a directory that holds
 * NOTHING BUT `.` AND `..` (asserted empty by `readdirSync` and by the child's own `os.listdir`),
 * with every input named by ABSOLUTE path from outside that directory, and with `--package-root`
 * as the ONLY route to the `diamond` package (PYTHONPATH is deleted from the child's environment,
 * so an ambient import cannot be what makes it work). Against an export this court builds through
 * the REAL producer path — `createMemoryOwner`, `stageKiraMemoryRecord`, `owner.grantFor`,
 * `owner.settle`, an approval artifact minted by AUMLOK's own `createApprovalReceipt` through
 * `tests/kira-approval-standin.mjs`, and `exportPublicEvidence` — the cold consumer reaches
 * `VERDICT: VERIFIED` with facets 1, 2 and 4 `VERIFIED` and facet 3 `MATCHED`, and, when the
 * caller names the approval lane, reports `APPROVAL_ARTIFACT_VERIFIED` with its operation binding
 * DERIVED from the supplied bytes.
 * The repo's own driver `scripts/kira/verify-public-evidence.py` (another lane's file: this court
 * READS it and never edits it) is run cold from the same empty directory over the same export.
 *
 * IT ALSO PROVES THE CONSUMER CAN GO RED. One flipped byte in each exported member — the receipt's
 * `sig`, the record's `recordId`, the Aura log's entry `hash`, and the object body — is a NAMED
 * refusal from the consumer's own vocabulary (`signature-invalid`, `record-identity-mismatch`,
 * `chain-tampered`, `object-tampered` / `APPROVAL_CONTENT_MISMATCH`), asserted twice: the run must
 * exit 1 with that name, and the SAME evidence handed back with `--expect <that name>` must exit 0,
 * which only happens when the observed verdict equals the demanded one. A disposable copy of the
 * vendored tree with `diamond/` removed fails by name (`SETUP: cannot import diamond.kira_evidence`),
 * and a copy with the consumer script itself removed fails naming the missing file, so this court
 * cannot pass on a missing dependency.
 *
 * TWO OLD FAIL-OPEN PROBES, FOLDED IN AS ARMS. The vendored pin was 12 commits behind Diamond's
 * `0d3cc66`, and the gap carried two live defects that /tmp probes demonstrated before the delta:
 * a signature FORGED WITH NO PRIVATE KEY under a small-order (identity) issuer key made the old
 * bytes answer `VERDICT: VERIFIED`, and a receipt whose `effectDigest` had been rewritten to 0*64
 * and RE-SIGNED was REFUSED without `--store` and VERIFIED with it, so naming MORE evidence
 * weakened the verdict. Both are arms of THIS court now, with no `/tmp` dependency and no fixture
 * that carries a secret key: the forgery is built here from the pinned module's own arithmetic, and
 * the re-signed receipt is signed by an Ed25519 keypair `node:crypto` mints inside this process,
 * whose private half is never serialised (the two files the court writes are checked for it). Each
 * arm carries its own control — the intact bundle verifies FIRST under the same consumer, and the
 * digest arm keeps the honest bundle verifying in BOTH store modes — so neither arm can pass by
 * refusing everything, and the second cannot pass by over-refusing.
 *
 * WHAT IT EXPLICITLY DOES NOT PROVE. The consumer prints its own ceilings and this court asserts
 * they are printed rather than pretending otherwise:
 *
 *   NO_CELL_EXECUTION_PROOF — "receipt verification checks signed bytes, not which program produced
 *     them." `CELL_EXECUTION: NOT_ESTABLISHED` is asserted, never upgraded.
 *   NO_LATESTNESS / COMPLETENESS: UNDETERMINED — a verified position shows the log CONTAINS that
 *     entry; it never shows the log is the tip of the world. This court asserts `NO_LATESTNESS`
 *     and `UNDETERMINED` verbatim.
 *   NO_HUMAN_ATTENDANCE / REPORTED_NOT_PROVEN_ATTENDANCE — `ATTENDANCE: reported-not-proven`. The
 *     approval lane proves a KEY signed bytes; nothing here shows a person was present. The
 *     approver is `tests/kira-approval-standin.mjs`, a daemon-free TEST DOUBLE, and — as that file
 *     says of itself — it imports the digest rule from the consuming lane, so a drift in that rule
 *     would move producer and verifier together and THIS COURT CANNOT SEE IT.
 *   NO_ABSENCE_OF_FORKS, NO_GLOBAL_REPLAY_PREVENTION, NO_WRITE_CLAIM, SAME_UID_ISSUER: the issuer
 *     key is generated by the disposable store under test and published with the evidence, so the
 *     anchor proves a pointer to that key and nothing about who held it.
 *   EVIDENCE_NEVER_AUTHORIZES. A verified record and receipt authorize nothing.
 *
 * It also does NOT prove the exporter's allowlist, determinism or refusals (that is
 * `tests/public-evidence.test.mjs`), and it does NOT prove the release's vendored copy: the
 * consumer under test is this checkout's `vendor/kira-export`, named by absolute path.
 *
 * DISPOSABLE STATE ONLY. One temporary root per run, removed afterwards. Every tampered document
 * and every broken dependency lives in a COPY under that root; the working tree, the release, the
 * live Kira store and `vendor/` are read and never written.
 */
import assert from 'node:assert/strict'
import { execFileSync, spawnSync } from 'node:child_process'
// The keypair the re-signed-digest arm needs is minted by the RUNTIME, not implemented here: no new
// curve code, and the private half can stay in this process's memory instead of in a fixture.
import { generateKeyPairSync, sign as signEd25519 } from 'node:crypto'
import {
  cpSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, realpathSync, rmSync, writeFileSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { basename, dirname, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { courtTemp, disposeCourtTemps } from './release-temp.mjs'

import { exportPublicEvidence, sha256 } from '../scripts/kira/public-evidence.mjs'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const { createMemoryOwner } = await import(pathToFileURL(join(ROOT, 'plugins/aukora-kira/lib/memory-owner.mjs')).href)
const { canonicalJSON, stageKiraMemoryRecord } = await import(pathToFileURL(join(ROOT, 'plugins/aukora-kira/lib/record.mjs')).href)
const { createApprover, writeApproval } = await import(pathToFileURL(join(ROOT, 'tests/kira-approval-standin.mjs')).href)

const MUTATE = process.argv.includes('--mutate')
const CONSUMER = join(ROOT, 'vendor/kira-export/scripts/verify-kira-evidence.py')
const PACKAGE_ROOT = join(ROOT, 'vendor/kira-export')
const DRIVER = join(ROOT, 'scripts/kira/verify-public-evidence.py')
const SUBJECT = `aukora:1:${'3c'.repeat(32)}`
const AT = '2026-09-08T00:00:00Z'
const NOTE = 'Cedar endpoint listens on port 8098'

// ── the harness: every arm runs, and with --mutate every arm must be able to go RED ────────────

let arms = 0
let failures = 0
const evidence = []

/**
 * Run one named arm. In the main pass a throw is a failure and never stops the suite. With
 * `--mutate` the arm is run a SECOND time with its own invariant broken in a disposable copy, and
 * that run MUST throw — and must throw the arm's own failed assertion, because a harness crash is
 * not a red arm.
 *
 * @param {string} name - the invariant this arm asserts.
 * @param {(broken: boolean) => string} body - returns one evidence line; throws when the invariant does not hold.
 */
function arm(name, body) {
  arms += 1
  let line
  try {
    line = body(false)
    evidence.push(`${String(arms).padStart(2)} ${name}\n     ${line}`)
    process.stdout.write(`  ok    ${name}\n          ${line}\n`)
  } catch (error) {
    failures += 1
    process.stdout.write(`  FAIL  ${name}\n        ${String(error.message).split('\n').join('\n        ')}\n`)
  }
  if (!MUTATE) return
  let red = null
  try {
    body(true)
  } catch (error) {
    red = error
  }
  if (red === null) {
    failures += 1
    process.stdout.write(`  FAIL  ${name} (--mutate)\n        the invariant was broken in a disposable copy and the arm STILL PASSED\n`)
    return
  }
  // *** A MUTANT MUST FAIL FOR THE PROPERTY IT BREAKS (Fable, 2026-09-26). *** The check below used to accept ANY
  // non-zero outcome as a catch, which made the mode vacuous in the way every lane keeps re-finding: a mutant that
  // died on a MISSING MODULE, or that refused without saying why, was counted CAUGHT while proving nothing about the
  // property it was supposed to break. A diagnosis that is empty, that is a traceback, or that is an import failure is
  // reported as CRASH-NOT-A-CATCH AND FAILS THIS COURT — the mutation has to have reached the check.
  const CRASH_OR_SILENT = /ModuleNotFoundError|ERR_MODULE_NOT_FOUND|Cannot find module|ImportError|Traceback \(most recent call last\)|SyntaxError|got -?\d+:\s*$/u
  if (red.name === 'AssertionError' && CRASH_OR_SILENT.test(String(red.message))) {
    failures += 1
    process.stdout.write(`  FAIL  ${name} (--mutate)\n        the broken variant CRASHED, or refused without naming a reason, so it did NOT test the property it breaks:\n        ${String(red.message).split('\n')[0].slice(0, 220)}\n`)
    return
  }
  if (red.name !== 'AssertionError') {
    failures += 1
    process.stdout.write(`  FAIL  ${name} (--mutate)\n        the broken variant CRASHED instead of failing an assertion: ${red.name}: ${red.message}\n`)
    return
  }
  process.stdout.write(`  red   ${name} (--mutate)\n          ${String(red.message).split('\n')[0]}\n`)
}

// ── the fixtures: a REAL settled store, exported by the REAL exporter ──────────────────────────

const work = courtTemp('kira-diamond-cold-', { realpath: true })
const emptyDir = join(work, 'empty-cwd')
mkdirSync(emptyDir, { recursive: true })
const notEmptyDir = join(work, 'not-empty-cwd')
mkdirSync(notEmptyDir, { recursive: true })
writeFileSync(join(notEmptyDir, 'a-stranger-left-this-here.txt'), 'this directory is not empty\n')

const stateDir = join(work, 'store')
mkdirSync(stateDir, { recursive: true, mode: 0o700 })
const owner = createMemoryOwner({ stateDir })
const approver = createApprover({ subject: SUBJECT })
const staged = stageKiraMemoryRecord({
  subject: SUBJECT, kind: 'observation', source: [], content: { note: NOTE }, links: [], privacy: 'local', createdAt: AT,
})
/** The REAL artifact: minted by AUMLOK's own `createApprovalReceipt` (see the standin's ceilings). */
const artifact = approver.approve(staged.memoryPut)
const artifactPath = join(work, 'approval-artifact.json')
writeApproval(artifactPath, artifact)
/** The REAL settlement: the plugin's own grant, the plugin's own signature, the plugin's own log. */
const settled = owner.settle(staged, owner.grantFor(staged.memoryPut), artifact, { subject: SUBJECT })
const STEM = settled.contentSha256

const anchorDir = join(work, 'anchors')
mkdirSync(anchorDir, { recursive: true })
const issuerAnchor = join(anchorDir, 'issuer')
writeFileSync(issuerAnchor, JSON.parse(readFileSync(join(stateDir, 'issuer.json'), 'utf8')).publicKey)
const approverAnchor = join(anchorDir, 'approver.pk')
writeFileSync(approverAnchor, `${approver.rawPublicKeyHex}\n`)

// A release record whose digests are computed from real bytes, naming the commit this court runs from.
const releaseDir = join(work, 'release')
mkdirSync(join(releaseDir, '.dsh-build'), { recursive: true })
const patchBytes = Buffer.from('a real byte string the release record describes\n', 'utf8')
writeFileSync(join(releaseDir, 'aukora-composition.patch.yml'), patchBytes)
const PRODUCER_COMMIT = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: ROOT, encoding: 'utf8' }).trim()
writeFileSync(join(releaseDir, '.dsh-build', 'genesis-artifacts.json'), `${JSON.stringify({
  formatVersion: 1,
  kind: 'dsh-artifact-record',
  producer: { node: process.version, platform: `${process.platform}-${process.arch}`, genesisCommit: PRODUCER_COMMIT },
  host: { fileCount: 1, bytes: patchBytes.byteLength, sha256: sha256(patchBytes) },
  entries: [{ path: 'aukora-composition.patch.yml', bytes: patchBytes.byteLength, sha256: sha256(patchBytes) }],
}, null, 2)}\n`)

const exportDir = join(work, 'export')
exportPublicEvidence({
  storeDir: stateDir,
  outDir: exportDir,
  producerCommit: PRODUCER_COMMIT,
  releaseDir,
  anchors: new Map([['issuer', issuerAnchor], ['approver', approverAnchor]]),
  approvals: new Map([[STEM, artifactPath]]),
})

// ── the runner: absolute paths, an empty cwd, and no PYTHONPATH to fall back on ────────────────

/** The child environment: PYTHONPATH is REMOVED, so `--package-root` is the only import route. */
const childEnv = { ...process.env }
delete childEnv.PYTHONPATH

/**
 * Run the frozen consumer with the given arguments from one cwd.
 * @param {string[]} args - consumer arguments.
 * @param {string} cwd - the process working directory.
 * @param {string} [consumer] - the consumer script (a DISPOSABLE copy, in the mutated variants).
 * @returns {{status: number|null, stdout: string, stderr: string}} the child result.
 */
function runConsumer(args, cwd, consumer = CONSUMER) {
  const result = spawnSync('python3', [consumer, ...args], { cwd, encoding: 'utf8', env: childEnv, timeout: 120_000 })
  return { status: result.status, stdout: result.stdout ?? '', stderr: result.stderr ?? '' }
}

/** The evidence-lane arguments, every path absolute and OUTSIDE the empty cwd. */
const evidenceArgs = (dir, packageRoot = PACKAGE_ROOT) => ([
  '--record', join(dir, 'evidence/records', `${STEM}.json`),
  '--receipt', join(dir, 'evidence/receipts', `${STEM}.json`),
  '--log', join(dir, 'evidence/aura.jsonl'),
  '--anchor', issuerAnchor,
  '--package-root', packageRoot,
])
/** The approval-ARTIFACT lane, as `verify-public-evidence.py` maps it: content bytes and anchor supplied separately. */
const artifactArgs = dir => ([
  '--artifact', join(dir, 'evidence/approvals', `${STEM}.json`),
  '--artifact-content', join(dir, 'evidence/objects', `${STEM}.json`),
  '--artifact-anchor', approverAnchor,
  '--artifact-subject', SUBJECT,
  '--store', stateDir,
])

/** Extract the framed JSON report, or fail: no block means no verdict was produced. */
function reportOf(stdout) {
  const begin = stdout.indexOf('REPORT-JSON-BEGIN')
  const end = stdout.indexOf('REPORT-JSON-END')
  assert.ok(begin >= 0 && end > begin, 'the consumer printed no framed REPORT-JSON block')
  return JSON.parse(stdout.slice(begin + 'REPORT-JSON-BEGIN'.length, end))
}

/** The refusal name the consumer printed, or undefined when it printed none. */
const refusalOf = stdout => (stdout.match(/^VERDICT: (?:REFUSED|UNSUPPORTED) {2}(\S+)$/m) ?? [])[1]

/** Copy one directory tree. Every tamper happens in a copy; the good export is never touched. */
function copyTree(from, to) {
  cpSync(from, to, { recursive: true })
  return to
}

/**
 * A DISPOSABLE COPY OF THE VENDORED DIAMOND WITH ONE CEILING REMOVED, for C3's mutation.
 *
 * `vendor/` is READ here and never written: the copy goes under the caller's `work`, only the copy is edited, and the removal is
 * ASSERTED to have matched — a mutation that silently removed nothing would leave the arm passing while claiming it broke something,
 * which is the defect family this court lives inside.
 *
 * @param {string} to - the disposable directory to build.
 * @returns {string} the copy's root, to hand `--package-root`.
 */
function vendoredCopyWithoutReplayCeiling(to) {
  copyTree(PACKAGE_ROOT, to)
  const file = join(to, 'diamond', 'kira_evidence.py')
  const source = readFileSync(file, 'utf8')
  const next = source.replace(/\s*"NO_GLOBAL_REPLAY_PREVENTION:[\s\S]*?"for the first time\.",/u, '')
  assert.notEqual(next, source, 'the mutation MUST match the ceiling it removes — a no-op mutation proves nothing')
  writeFileSync(file, next)
  return to
}

/**
 * Flip exactly ONE byte where it matters, keeping the document parseable: a hex character moves to
 * another hex character, any other letter changes case.
 *
 * @param {string} path - the file to edit (always inside a disposable copy).
 * @param {string} needle - the text the byte must follow.
 * @returns {string} a description of the flip, for the evidence line.
 */
function flipOneByte(path, needle) {
  const bytes = readFileSync(path)
  const at = bytes.indexOf(Buffer.from(needle, 'utf8'))
  assert.ok(at >= 0, `${basename(path)} does not contain ${JSON.stringify(needle)}`)
  const index = at + Buffer.byteLength(needle)
  const before = bytes[index]
  const character = String.fromCharCode(before)
  const HEX = '0123456789abcdef'
  bytes[index] = HEX.includes(character)
    ? HEX.charCodeAt((HEX.indexOf(character) + 1) % 16)
    : (before >= 0x41 && before <= 0x5a ? before + 0x20 : before - 0x20)
  assert.notEqual(bytes[index], before, 'a flip must change a byte')
  writeFileSync(path, bytes)
  return `${basename(path)} byte ${index}: ${character} -> ${String.fromCharCode(bytes[index])}`
}

/**
 * The mutations: one check defeated in a DISPOSABLE copy of the vendored consumer, so a tamper arm
 * can be shown to go red. If an arm still passed against a consumer that had stopped making the
 * check it asserts, the arm would be measuring nothing at all. Each edit is asserted to have
 * matched, so a consumer whose text moved fails loudly here instead of silently rubber-stamping.
 *
 * NOTHING UNDER `vendor/` IS EVER WRITTEN: the copy is made under this run's temporary root.
 */
const RUBBER_STAMPS = {
  signature: ['    if len(public_key) != 32 or len(signature) != 64:\n        return False\n',
    '    return True  # RUBBER STAMP: signature verification defeated in a disposable copy\n'],
  identity: ['    return "kira:" + digest.hexdigest()',
    '    return record["recordId"]  # RUBBER STAMP: identity recomputation defeated\n'],
  chain: ['    prev = AURA_RECORD_DOMAIN\n    for index, entry in enumerate(entries[:upto], start=1):\n',
    '    return {"ok": True, "head": entries[upto - 1].get("hash"), "verifiedEntries": min(upto, len(entries))}  # RUBBER STAMP\n'],
  object: ['            raise Refusal("object-tampered", "the object bytes do not hash to the named digest")',
    '            pass  # RUBBER STAMP: object digest check defeated\n'],
  // The small-order rule is the ONLY thing standing between a no-key forgery and a verdict: with it
  // removed, the Ed25519 equation the forgery satisfies holds, and the pre-delta bytes verified it.
  smallOrder: ['    if _scalar_mult(point, 8) == (0, 1):\n        raise Refusal("ed25519-small-order", "small-order points are not accepted")\n',
    '    pass  # RUBBER STAMP: the small-order rule is defeated in a disposable copy\n'],
  // The receipt/Aura digest binding, which the store path used to skip: with it removed, a re-signed
  // `effectDigest` of 0*64 is accepted in BOTH modes — the fail-open this arm exists to catch.
  effectDigest: ['    if receipt["effectDigest"] != content_sha:\n        raise Refusal("effect-digest-mismatch",\n                      "the receipt and its Aura entry name different content digests")\n',
    '    pass  # RUBBER STAMP: the receipt/Aura effect-digest binding is defeated in a disposable copy\n'],
}

/**
 * A disposable copy of `vendor/kira-export` with ONE check defeated.
 * @param {keyof typeof RUBBER_STAMPS} check - which check to defeat.
 * @returns {string} the copy's root, for `--package-root`.
 */
function rubberStampedConsumer(check) {
  const copy = join(work, `consumer-stamped-${check}`)
  cpSync(PACKAGE_ROOT, copy, { recursive: true })
  const target = join(copy, 'diamond/kira_evidence.py')
  const [from, to] = RUBBER_STAMPS[check]
  const text = readFileSync(target, 'utf8')
  assert.ok(text.includes(from), `the rubber stamp for ${check} no longer matches the vendored consumer`)
  writeFileSync(target, text.replace(from, to))
  return copy
}

/**
 * One tampered member, asserted the strongest way available: the run exits 1 with the DEMANDED
 * name, and the same evidence handed back with `--expect <name>` exits 0, which happens only when
 * the observed verdict equals the demanded one.
 *
 * @param {string} name - the refusal name the consumer must produce.
 * @param {string} relative - the exported member to flip a byte in.
 * @param {string} needle - where in that member.
 * @param {{lane?: 'artifact'|'store', consumer?: string}} [options] - which lane reads that member, and which consumer runs.
 * @returns {string} the evidence line.
 */
function tamperArm(name, relative, needle, options = {}) {
  const copy = copyTree(exportDir, join(work, `tamper-${name.replaceAll(/[^a-z0-9]+/giu, '-')}`))
  const flipped = flipOneByte(join(copy, relative), needle)
  const lane = options.lane === 'artifact' ? artifactArgs(copy)
    : options.lane === 'store' ? ['--store', join(copy, 'evidence')] : []
  const consumer = options.consumer === undefined ? CONSUMER : join(options.consumer, 'scripts/verify-kira-evidence.py')
  const packageRoot = options.consumer ?? PACKAGE_ROOT
  const observed = runConsumer([...evidenceArgs(copy, packageRoot), ...lane], emptyDir, consumer)
  assert.equal(observed.status, 1, `expected exit 1 on the tampered member, got ${observed.status}: ${observed.stderr}`)
  assert.equal(refusalOf(observed.stdout), name,
    `expected refusal ${name}, got ${String(refusalOf(observed.stdout))}`)
  const demanded = runConsumer([...evidenceArgs(copy, packageRoot), ...lane, '--expect', name], emptyDir, consumer)
  assert.equal(demanded.status, 0,
    `--expect ${name} did not exit 0, so the observed verdict was not ${name}: ${demanded.stdout.split('\n').slice(-3).join(' | ')}`)
  assert.match(demanded.stdout, new RegExp(`^EXPECTATION: ${name} OBSERVED$`, 'mu'))
  return `${flipped}; refused by name \`${name}\` (exit 1), and \`--expect ${name}\` exits 0`
}

process.stdout.write(`kira × diamond cold consumer — empty cwd, real export${MUTATE ? ' (--mutate)' : ''}\n`)
process.stdout.write(`producer commit ${PRODUCER_COMMIT}\nrecord ${staged.recordId}\n\n`)

// ── 1. the empty-directory property itself ─────────────────────────────────────────────────────

arm('the consumer runs with its cwd a LITERAL empty directory (nothing but . and ..)', broken => {
  // Measured by the child, not by this process: the same spawn options the consumer runs under.
  const dir = broken ? notEmptyDir : emptyDir
  const probe = spawnSync('python3', ['-c', 'import os;print(os.getcwd());print(sorted(os.listdir(".")))'],
    { cwd: dir, encoding: 'utf8', env: childEnv })
  const [reportedCwd, listing] = probe.stdout.trimEnd().split('\n')
  assert.equal(reportedCwd, dir, 'the child did not run in the directory this court named')
  assert.deepEqual(readdirSync(dir), [], 'the cwd is not empty')
  assert.equal(listing, '[]', `the child sees ${listing} in its own cwd`)
  return `child cwd ${reportedCwd}; os.listdir(".") = ${listing}; consumer is ${CONSUMER.startsWith(dir) ? 'INSIDE' : 'outside'} that cwd`
})

// ── 2. the cold verification of the real export ────────────────────────────────────────────────

arm('the cold consumer VERIFIES the real export: four facets, exit 0, ceilings intact', broken => {
  // *** C3: THE MUTATION IS THE CEILING ITSELF, REMOVED FROM A SCRATCH COPY OF THE VENDORED TREE. *** This arm used to flip a byte in
  // the exported receipt, so under `--mutate` it failed at the SIGNATURE and the ceilings assertions below were never exercised at all:
  // an arm whose only broken variant is somewhere else cannot prove the thing it names. The byte flips keep their own arms (the signed
  // receipt, record, aura-log and object-body arms), so this arm's invariant is free to be the ceilings.
  //
  // `vendor/` IS READ AND NEVER WRITTEN — the copy is disposable, under this court's own `work`, and only the COPY is edited.
  const scratch = broken ? vendoredCopyWithoutReplayCeiling(join(work, 'vendor-no-replay-ceiling')) : null
  // `flipped` keeps its name for the evidence line below; what it now names is the mutation, not a byte.
  const flipped = scratch === null ? null : 'the NO_GLOBAL_REPLAY_PREVENTION ceiling removed from a scratch copy of vendor/kira-export'
  const run = runConsumer([...evidenceArgs(exportDir, scratch ?? PACKAGE_ROOT), '--expect', 'verified', '--json'], emptyDir)
  // THE DIAGNOSIS MUST BE READABLE, because the mutant's failure IS the evidence: an empty message made a crash look
  // like a catch in `--mutate`. stdout carries the consumer's own verdict and refusal names; stderr carries crashes.
  assert.equal(run.status, 0, `expected exit 0 from the cold consumer, got ${run.status}: ${run.stderr}${run.stdout}`)
  assert.match(run.stdout, /^EXPECTATION: verified OBSERVED$/mu)
  assert.match(run.stdout, /^VERDICT: VERIFIED \(the checks above hold for these bytes\)$/mu)
  for (const facet of ['1. RECORD IDENTITY AND CONTENT DIGEST', '2. SIGNATURE AND CANONICALIZATION (RFC 8785 JCS)',
    '3. ISSUER ANCHOR', '4. HISTORICAL POSITION']) {
    assert.ok(run.stdout.includes(facet), `the report is missing facet ${facet}`)
  }
  // Facet 3 reports MATCHED, not VERIFIED, because an anchor is a comparison rather than a check.
  assert.equal((run.stdout.match(/^ {3}VERDICT {13}: VERIFIED$/gmu) ?? []).length, 3, 'facets 1, 2 and 4 must report VERIFIED')
  assert.equal((run.stdout.match(/^ {3}VERDICT {13}: MATCHED$/gmu) ?? []).length, 1, 'facet 3 must report the anchor MATCHED')
  // The ceilings are asserted AS PRINTED. A verdict that dropped them would be a stronger claim.
  for (const ceiling of ['ATTENDANCE: reported-not-proven', 'CELL_EXECUTION: NOT_ESTABLISHED',
    'COMPLETENESS: UNDETERMINED', 'LATESTNESS: NO_LATESTNESS', 'OPERATOR_PRESENCE: NOT_ESTABLISHED',
    'EVIDENCE NEVER AUTHORIZES: a verified record and receipt authorize nothing.',
    // *** C3: THE SIXTH CONSUMER CEILING WAS MISSING — NO_GLOBAL_REPLAY_PREVENTION. *** The consumer renders every vendored ceiling
    // verbatim, so a consumer that dropped this one would claim more than the module it consumes: that a receipt cannot be presented
    // twice. Asserted in the module's own words, concatenated exactly as `kira_evidence.py` wraps them.
    `NO_GLOBAL_REPLAY_PREVENTION: a recorded receipt can be presented again forever. Nothing here is a nonce book, and no check `
    + `in this module can show a document is being presented for the first time.`]) {
    assert.ok(run.stdout.includes(ceiling), `the consumer did not report its ceiling: ${ceiling}`)
  }
  // AUTHORITY_MODE is the approval CLASS THE RECEIPT CARRIES, suffixed `-reported`: carried by the
  // input, never verified as a proof mode. Tied to the real receipt rather than hard-coded.
  const approvalClass = /** @type {{approval: {approvalClass: string}}} */ (settled.receipt).approval.approvalClass
  assert.match(run.stdout, new RegExp(`^AUTHORITY_MODE: ${approvalClass}-reported$`, 'mu'),
    'the authority mode must be the class the receipt reports, and say that it is only reported')
  const report = reportOf(run.stdout)
  assert.equal(report.verified, true)
  assert.equal(report.verdict, 'verified')
  assert.equal(report.attendance, 'reported-not-proven')
  assert.equal(report.execution.status, 'NOT_ESTABLISHED')
  assert.equal(report.authorityScope.mode, `${approvalClass}-reported`)
  assert.equal(report.authorityScope.operatorPresence, 'NOT_ESTABLISHED')
  assert.equal(report.retention.completeness, 'UNDETERMINED')
  assert.equal(report.retention.latestness, 'NO_LATESTNESS')
  assert.equal(report.record.claimedRecordId, staged.recordId, 'the verified record is not the one this court settled')
  assert.equal(report.receipt.verified, true)
  assert.equal(report.position.position, settled.sequence)
  // And the empty cwd is still empty: the consumer wrote nothing into the directory it ran from.
  assert.deepEqual(readdirSync(emptyDir), [], 'the consumer wrote into its cwd')
  return `${flipped === null ? 'intact export' : `MUTATED (${flipped})`}; exit 0, VERDICT: VERIFIED, `
    + `facets 1/2/4 VERIFIED and facet 3 MATCHED, record ${report.record.claimedRecordId.slice(0, 14)}…, `
    + `position ${report.position.position}; ceilings as printed: ATTENDANCE=${report.attendance}, `
    + `CELL_EXECUTION=${report.execution.status}, AUTHORITY_MODE=${report.authorityScope.mode}, `
    + `COMPLETENESS=${report.retention.completeness}, LATESTNESS=${report.retention.latestness}`
})

arm('the cold consumer checks the REAL owner-approval ARTIFACT offline, from the same empty cwd', broken => {
  // MUTATION: one byte of the signed operation digest is flipped in a disposable copy of the artifact.
  const dir = broken ? copyTree(exportDir, join(work, 'artifact-mutated')) : exportDir
  const flipped = broken ? flipOneByte(join(dir, 'evidence/approvals', `${STEM}.json`), '"operationDigest": "') : null
  const run = runConsumer([...evidenceArgs(dir), ...artifactArgs(dir), '--expect', 'verified', '--json'], emptyDir)
  assert.equal(run.status, 0, `expected exit 0 with the artifact lane, got ${run.status}: ${run.stderr}${run.stdout}`)
  assert.match(run.stdout, /^ {3}STATUS {14}: APPROVAL_ARTIFACT_VERIFIED$/mu)
  assert.match(run.stdout, /OPERATION_BINDING_VERIFIED \(DERIVED from the supplied content bytes\)/u)
  assert.match(run.stdout, /^ {3}signature {11}: APPROVAL_SIGNATURE_VALID \(anchor: hex\)$/mu)
  // The lane verifies a KEY over BYTES; authorization and attendance are asserted UNCHANGED.
  assert.match(run.stdout, /authorization OWNER_APPROVAL_UNCHECKED/u)
  const report = reportOf(run.stdout)
  assert.equal(report.verified, true)
  assert.equal(report.approval.status, 'APPROVAL_ARTIFACT_VERIFIED')
  assert.deepEqual(readdirSync(emptyDir), [], 'the artifact-lane run wrote into its cwd')
  return `${flipped === null ? 'intact artifact' : `MUTATED (${flipped})`}; exit 0, APPROVAL_ARTIFACT_VERIFIED, `
    + 'binding DERIVED from the object bytes, authorization still OWNER_APPROVAL_UNCHECKED'
})

// ── 3. one flipped byte is a NAMED refusal, in every member the consumer reads ─────────────────

arm('a flipped byte in the exported RECEIPT is refused by name (signature-invalid)', broken =>
  `${soundLine(`evidence/receipts/${STEM}.json`)}; ${tamperArm('signature-invalid', `evidence/receipts/${STEM}.json`, '"sig": "', {
    // MUTATION: a consumer whose Ed25519 check returns True whatever it is handed.
    ...(broken ? { consumer: rubberStampedConsumer('signature') } : {}),
  })}`)

arm('a flipped byte in the exported RECORD is refused by name (record-identity-mismatch)', broken =>
  `${soundLine(`evidence/records/${STEM}.json`)}; ${tamperArm('record-identity-mismatch', `evidence/records/${STEM}.json`, '"recordId": "kira:', {
    // MUTATION: a consumer that recomputes no identity and returns the one it was handed.
    ...(broken ? { consumer: rubberStampedConsumer('identity') } : {}),
  })}`)

arm('a flipped byte in the exported AURA LOG is refused by name (chain-tampered)', broken =>
  `${soundLine('evidence/aura.jsonl')}; ${tamperArm('chain-tampered', 'evidence/aura.jsonl', '"hash":"', {
    // MUTATION: a consumer whose chain walk returns ok without hashing a single entry.
    ...(broken ? { consumer: rubberStampedConsumer('chain') } : {}),
  })}`)

arm('a flipped byte in the exported OBJECT BODY is refused by name when the caller names it', broken => {
  const sound = soundLine(`evidence/objects/${STEM}.json`)
  // MUTATION: a consumer whose object-digest check is defeated — the bytes are read and accepted.
  const stamped = broken ? { consumer: rubberStampedConsumer('object') } : {}
  const store = tamperArm('object-tampered', `evidence/objects/${STEM}.json`, '"note":"', { lane: 'store', ...stamped })
  const artifact = tamperArm('APPROVAL_CONTENT_MISMATCH', `evidence/objects/${STEM}.json`, '"note":"', { lane: 'artifact' })
  // IN THE EVIDENCE-ONLY LANE THE OBJECT IS NOT READ AT ALL. That is a measured property, not a
  // gap in this arm: the object is named by --store or --artifact-content, and an unread byte
  // cannot be refused. Asserted here so the arm states what it did NOT check.
  const named = copyTree(exportDir, join(work, 'object-unread'))
  const note = flipOneByte(join(named, 'evidence/objects', `${STEM}.json`), '"note":"')
  const run = runConsumer([...evidenceArgs(named), '--expect', 'verified'], emptyDir)
  assert.equal(run.status, 0, `the object byte changed the evidence-only verdict: ${run.stdout.split('\n').slice(-3).join(' | ')}`)
  return `${sound}; ${store}; as --artifact-content: ${artifact}; not read by the evidence-only lane, so a flipped `
    + `byte there is NOT refused (exit 0 VERIFIED) — ${note}`
})

/**
 * The unmutated half of a tamper arm: the SAME member, unchanged, must verify — otherwise the arm
 * would be measuring a document that was already broken.
 * @param {string} relative - the member the tamper arm flips.
 * @returns {string} the evidence line.
 */
function soundLine(relative) {
  const run = runConsumer([...evidenceArgs(exportDir), '--expect', 'verified'], emptyDir)
  assert.equal(run.status, 0, `the untouched member ${relative} did not verify: ${run.stdout.split('\n').slice(-3).join(' | ')}`)
  return `${relative} unchanged: exit 0, VERIFIED (so the flipped byte, not the document, is the refusal)`
}

// ── 3b. the two fail-open probes, folded in: a no-key forgery, and a re-signed digest ──────────

/**
 * Forge the exported receipt's signature in a DISPOSABLE copy, using NO PRIVATE KEY.
 *
 * WHAT THE FORGERY IS, and why it is not just a flipped byte. The issuer key is written as the
 * compressed IDENTITY point (y = 1, x = 0) — a point of order 1, for which no private key exists,
 * so no honest signature can ever be produced under it. The signature is the pair `R = S·B`,
 * `s = S` for a scalar the forger simply picks: Ed25519's verification equation `sB = R + kA` then
 * holds for EVERY challenge k, because multiplying the identity point by k yields the identity.
 * The forged bytes are therefore STRUCTURALLY PERFECT — a canonical R, s inside the group order,
 * 64 bytes — and the only thing wrong with them is that the named key is small-order. A consumer
 * that skips the small-order rule verifies this forgery; that is exactly the fail-open the vendored
 * delta closed, and it is why this arm is not the flipped-byte arm above.
 *
 * The arithmetic is the pinned module's own (`diamond.ed25519`), and the measured claims are made
 * here rather than asserted in prose: the identity point is small-order, the equation holds under
 * it in the module's arithmetic AND in the consumer's own (`diamond.kira_evidence`), while the
 * consumer's own strict verifier REFUSES the very signature the equation accepts. A re-pin that
 * moved those names fails loudly here instead of quietly measuring nothing.
 *
 * @param {string} dir - a disposable COPY of the export whose receipt and anchor are rewritten.
 * @returns {{issuerPk: string, anchor: string, receipt: string, sigBytes: number, equationHolds: boolean, consumerEquationHolds: boolean, consumerVerify: boolean, strictRefusal: string}} the forgery, as measured.
 */
function forgeReceiptSignature(dir) {
  const receiptPath = join(dir, 'evidence/receipts', `${STEM}.json`)
  const anchorPath = join(dir, 'forged.anchor')
  const script = String.raw`
import json, sys
from hashlib import sha512
from pathlib import Path
PKG, RECEIPT, ANCHOR = sys.argv[1], Path(sys.argv[2]), Path(sys.argv[3])
sys.path.insert(0, PKG)
from diamond import ed25519 as ed           # the pinned module's own curve arithmetic
from diamond import kira_evidence as ke     # the pinned module's own JCS and verifier

IDENTITY = (0, 1)                           # y = 1: order 1. No private key exists.
S = 4242                                    # the forger's scalar; no key is derived from it
R_POINT = ed._mul(S, ed.B)
R_BYTES = ed._encode_point(R_POINT)
sig = R_BYTES + S.to_bytes(32, "little")
identity_bytes = ed._encode_point(IDENTITY)

receipt = json.loads(RECEIPT.read_text(encoding="utf-8"))
body = {k: v for k, v in receipt.items() if k not in ("sig", "issuerPk")}
message = f"{receipt['kind']}\n".encode("utf-8") + ke.jcs_bytes(body)

challenge = int.from_bytes(sha512(R_BYTES + identity_bytes + message).digest(), "little") % ed.L
consumer_challenge = int.from_bytes(sha512(R_BYTES + identity_bytes + message).digest(), "little") % ke._L
equation_holds = ed._mul(S, ed.B) == ed._add(R_POINT, ed._mul(challenge, IDENTITY))
consumer_equation_holds = (
    ke._compress(ke._scalar_mult(ke._B, S))
    == ke._compress(ke._edwards_add(ke._decompress(R_BYTES),
                                    ke._scalar_mult(IDENTITY, consumer_challenge))))
try:
    ed._decode_point(identity_bytes)
    strict_refusal = None
except ValueError as exc:
    strict_refusal = str(exc)

assert ed._mul(2, IDENTITY) == IDENTITY, "the identity point is not small-order"
assert equation_holds, "the forged signature does not satisfy the verification equation"
assert consumer_equation_holds, "the consumer's own arithmetic rejects the forged equation"
assert strict_refusal and "small-order" in strict_refusal, f"unexpected strict refusal: {strict_refusal!r}"

receipt["issuerPk"] = identity_bytes.hex()
receipt["sig"] = sig.hex()
RECEIPT.write_text(json.dumps(receipt, sort_keys=True), encoding="utf-8")
ANCHOR.write_text(identity_bytes.hex() + "\n", encoding="utf-8")
print(json.dumps({
    "issuerPk": identity_bytes.hex(), "sigBytes": len(sig),
    "equationHolds": equation_holds, "consumerEquationHolds": consumer_equation_holds,
    "consumerVerify": ke.ed25519_verify(identity_bytes, message, sig),
    "strictRefusal": strict_refusal,
}))
`
  const run = spawnSync('python3', ['-c', script, PACKAGE_ROOT, receiptPath, anchorPath],
    { cwd: work, encoding: 'utf8', env: childEnv })
  assert.equal(run.status, 0, `the forgery generator failed: ${run.stderr}`)
  const forged = JSON.parse(run.stdout.trim())
  assert.equal(forged.issuerPk, `01${'00'.repeat(31)}`,
    'the issuer key must be the identity point this court names independently of the generator')
  assert.equal(forged.sigBytes, 64, 'the forgery must be structurally a signature (64 bytes)')
  assert.equal(forged.equationHolds, true, 'the forgery must satisfy the Ed25519 equation under the identity key')
  assert.equal(forged.consumerEquationHolds, true, 'the consumer\'s own arithmetic must accept the forged equation')
  assert.equal(forged.consumerVerify, false, 'the consumer\'s own strict verifier must refuse the forgery')
  assert.match(forged.strictRefusal, /small-order/u, 'the refusal under test must be the small-order rule')
  return { ...forged, receipt: receiptPath, anchor: anchorPath }
}

/**
 * Replace the exported receipt in a DISPOSABLE copy with one RE-SIGNED under a keypair generated in
 * THIS PROCESS, optionally rewriting `effectDigest` to 0*64 first.
 *
 * WHY RE-SIGN AT ALL. `effectDigest` is inside the signed body, so a mutated digest carrying the
 * original signature would be refused as `signature-invalid` and would prove nothing about the
 * digest binding. The mutation is only interesting when the signature over it is VALID — which is
 * why the refusal the arm demands is `effect-digest-mismatch`, a code a broken signature can never
 * produce.
 *
 * WHY A GENERATED KEYPAIR, stated because it is a property and not an implementation detail. The
 * exported receipt is signed by the store's own issuer key and this court does not hold its private
 * half; more to the point, NO FIXTURE MAY CARRY A SECRET KEY INTO THE REPOSITORY. `node:crypto`
 * mints a fresh Ed25519 keypair here per call: the private half lives only in this process's memory,
 * is never returned, never written to the working tree and never written to any temporary directory,
 * and the anchor file holds the PUBLIC half only. Both files this function writes are then CHECKED
 * for the private half's bytes rather than trusted to omit them.
 *
 * @param {string} dir - a disposable COPY of the export whose receipt is replaced.
 * @param {string} stem - the file stem for the anchor this run publishes.
 * @param {boolean} zeroDigest - whether to rewrite `effectDigest` to 0*64 before signing.
 * @returns {{receipt: string, anchor: string, issuerPk: string, effectDigest: string, privateHalfBytes: number, carriesPrivateKey: boolean}} the re-signed pair and what was checked about it.
 */
function resignReceipt(dir, stem, zeroDigest) {
  const { publicKey, privateKey } = generateKeyPairSync('ed25519')
  const issuerPk = publicKey.export({ type: 'spki', format: 'der' }).subarray(-32).toString('hex')
  const receiptPath = join(dir, 'evidence/receipts', `${STEM}.json`)
  const anchorPath = join(dir, `${stem}.anchor`)
  const receipt = JSON.parse(readFileSync(join(exportDir, 'evidence/receipts', `${STEM}.json`), 'utf8'))
  delete receipt.sig
  receipt.issuerPk = issuerPk
  if (zeroDigest) receipt.effectDigest = '0'.repeat(64)
  // The signed body is every field except `sig` and `issuerPk` — the same rule the consumer
  // restates — so the receipt can NAME this key without breaking the signature.
  const body = Object.fromEntries(Object.entries(receipt).filter(([key]) => key !== 'issuerPk'))
  const signedBytes = Buffer.concat([
    Buffer.from(`${receipt.kind}\n`, 'utf8'),
    Buffer.from(canonicalJSON(body), 'utf8'),
  ])
  receipt.sig = signEd25519(null, signedBytes, privateKey).toString('hex')
  assert.equal(receipt.sig.length, 128, 'an Ed25519 signature is 64 bytes of hex')
  writeFileSync(receiptPath, `${JSON.stringify(receipt, null, 2)}\n`)
  writeFileSync(anchorPath, `${issuerPk}\n`)
  // THE SECRET-KEY-FREE PROPERTY, MEASURED: the private half is exported here only to be searched
  // for in the two files just written, and it is never printed or returned.
  const privateHalf = privateKey.export({ type: 'pkcs8', format: 'der' })
  const carriesPrivateKey = readFileSync(receiptPath).includes(privateHalf)
    || readFileSync(anchorPath).includes(privateHalf)
  return {
    receipt: receiptPath, anchor: anchorPath, issuerPk, effectDigest: receipt.effectDigest,
    privateHalfBytes: privateHalf.byteLength, carriesPrivateKey,
  }
}

/**
 * The evidence-lane arguments for a disposable copy whose RECEIPT and ANCHOR this court wrote
 * itself: the record and the log are the real exported ones, the anchor names the key that signed.
 *
 * @param {string} dir - the disposable copy.
 * @param {string} anchor - the anchor file naming the signing key.
 * @param {string} packageRoot - the tree the consumer imports `diamond` from.
 * @param {boolean} [store] - whether to name the copy's own evidence directory as the store.
 * @returns {string[]} consumer arguments.
 */
const courtSignedArgs = (dir, anchor, packageRoot, store = false) => ([
  '--record', join(dir, 'evidence/records', `${STEM}.json`),
  '--receipt', join(dir, 'evidence/receipts', `${STEM}.json`),
  '--log', join(dir, 'evidence/aura.jsonl'),
  '--anchor', anchor,
  '--package-root', packageRoot,
  ...(store ? ['--store', join(dir, 'evidence')] : []),
])

arm('a signature FORGED with NO private key under a small-order issuer key is refused by name (signature-invalid)', broken => {
  // MUTATION: the small-order rule removed — the pre-delta bytes, and the ONLY check this forgery
  // trips. Nothing else about the consumer is weakened, so a red here names the hole itself.
  const stamped = broken ? rubberStampedConsumer('smallOrder') : null
  const consumer = stamped === null ? CONSUMER : join(stamped, 'scripts/verify-kira-evidence.py')
  const packageRoot = stamped ?? PACKAGE_ROOT
  // THE INTACT MEMBER VERIFIES FIRST, IN THE SAME RUN AND UNDER THE SAME CONSUMER: an arm that
  // refused everything would fail here, as would a mutation that broke honest evidence.
  const sound = runConsumer([...evidenceArgs(exportDir, packageRoot), '--expect', 'verified'], emptyDir, consumer)
  assert.equal(sound.status, 0, `the untouched export did not verify: ${sound.stdout.split('\n').slice(-3).join(' | ')}`)
  assert.match(sound.stdout, /^VERDICT: VERIFIED \(the checks above hold for these bytes\)$/mu)
  const dir = copyTree(exportDir, join(work, 'forged-signature'))
  const forged = forgeReceiptSignature(dir)
  const observed = runConsumer(courtSignedArgs(dir, forged.anchor, packageRoot), emptyDir, consumer)
  assert.equal(observed.status, 1,
    `the forged signature was NOT refused: exit ${observed.status} — ${observed.stdout.split('\n').slice(-3).join(' | ')}`)
  assert.equal(refusalOf(observed.stdout), 'signature-invalid',
    `expected the refusal \`signature-invalid\`, got ${String(refusalOf(observed.stdout))}`)
  const demanded = runConsumer([...courtSignedArgs(dir, forged.anchor, packageRoot), '--expect', 'signature-invalid'], emptyDir, consumer)
  assert.equal(demanded.status, 0,
    `\`--expect signature-invalid\` did not exit 0: ${demanded.stdout.split('\n').slice(-3).join(' | ')}`)
  assert.match(demanded.stdout, /^EXPECTATION: signature-invalid OBSERVED$/mu)
  return `intact export VERIFIED first (exit 0, same consumer); forgery: issuerPk = the identity point `
    + `${forged.issuerPk.slice(0, 8)}… (order 1, NO private key) with a structurally perfect 64-byte signature whose `
    + `equation the CONSUMER'S OWN arithmetic confirms (sB = R + kA) while its own strict verifier refuses it `
    + `(${forged.strictRefusal}); consumer: exit 1, REFUSED \`signature-invalid\`, and \`--expect signature-invalid\` exits 0`
})

arm('effectDigest rewritten to 0*64 and RE-SIGNED is refused by name (effect-digest-mismatch) in BOTH store modes, honest bundle still VERIFIED', broken => {
  // MUTATION: the receipt/Aura effect-digest binding removed — the check the store path used to
  // skip, and the one this arm asserts. Nothing else about the consumer is weakened.
  const stamped = broken ? rubberStampedConsumer('effectDigest') : null
  const consumer = stamped === null ? CONSUMER : join(stamped, 'scripts/verify-kira-evidence.py')
  const packageRoot = stamped ?? PACKAGE_ROOT
  // CONTROL 1: the bundle AS EXPORTED (owner key, evidence anchor) verifies in BOTH modes, and the
  // store mode is shown to have READ the stored bytes, so "with-store" is not "store ignored".
  const exported = [false, true].map(store => runConsumer([
    ...evidenceArgs(exportDir, packageRoot),
    ...(store ? ['--store', join(exportDir, 'evidence')] : []), '--expect', 'verified',
  ], emptyDir, consumer))
  for (const [index, run] of exported.entries()) {
    const mode = index === 0 ? 'no-store' : 'with-store'
    assert.equal(run.status, 0, `the exported bundle did not verify in ${mode} mode: ${run.stdout.split('\n').slice(-3).join(' | ')}`)
    assert.match(run.stdout, /^VERDICT: VERIFIED \(the checks above hold for these bytes\)$/mu)
  }
  assert.match(exported[1].stdout, /^ {3}object bytes +: \d+ \(sha256 == /mu,
    'the with-store run did not read the stored object bytes, so the mode is not what it claims')
  // CONTROL 2: this court's signing rule IS the consumer's rule. A receipt re-signed over the TRUE
  // digest verifies in both modes, so the zeroed refusal below cannot be this court mis-signing.
  const honestDir = copyTree(exportDir, join(work, 'resigned-honest'))
  const honest = resignReceipt(honestDir, 'honest', false)
  assert.equal(honest.carriesPrivateKey, false, 'a generated private key reached a written fixture file')
  const honestRuns = [false, true].map(store =>
    runConsumer(courtSignedArgs(honestDir, honest.anchor, packageRoot, store), emptyDir, consumer))
  for (const [index, run] of honestRuns.entries()) {
    const mode = index === 0 ? 'no-store' : 'with-store'
    assert.equal(run.status, 0, `the re-signed HONEST receipt did not verify in ${mode} mode: ${run.stdout.split('\n').slice(-3).join(' | ')}`)
    assert.match(run.stdout, /^VERDICT: VERIFIED \(the checks above hold for these bytes\)$/mu)
  }
  // THE MUTATION UNDER TEST: only `effectDigest` changes, and the signature over the changed body is
  // VALID — so the refusal below is the digest binding, in BOTH modes, not the signature.
  const zeroedDir = copyTree(exportDir, join(work, 'resigned-zero-digest'))
  const zeroed = resignReceipt(zeroedDir, 'zero-digest', true)
  assert.equal(zeroed.effectDigest, '0'.repeat(64), 'the mutated receipt must carry the zeroed digest')
  assert.equal(zeroed.carriesPrivateKey, false, 'a generated private key reached a written fixture file')
  const modes = []
  for (const store of [false, true]) {
    const mode = store ? 'with-store' : 'no-store'
    const run = runConsumer(courtSignedArgs(zeroedDir, zeroed.anchor, packageRoot, store), emptyDir, consumer)
    assert.equal(run.status, 1,
      `the re-signed 0*64 digest was NOT refused in ${mode} mode: exit ${run.status} — ${run.stdout.split('\n').slice(-3).join(' | ')}`)
    assert.equal(refusalOf(run.stdout), 'effect-digest-mismatch',
      `in ${mode} mode expected \`effect-digest-mismatch\`, got ${String(refusalOf(run.stdout))}`)
    const demanded = runConsumer([...courtSignedArgs(zeroedDir, zeroed.anchor, packageRoot, store), '--expect', 'effect-digest-mismatch'], emptyDir, consumer)
    assert.equal(demanded.status, 0,
      `\`--expect effect-digest-mismatch\` did not exit 0 in ${mode} mode: ${demanded.stdout.split('\n').slice(-3).join(' | ')}`)
    assert.match(demanded.stdout, /^EXPECTATION: effect-digest-mismatch OBSERVED$/mu)
    modes.push(mode)
  }
  return `exported bundle VERIFIED in both modes (with-store READ the object bytes); re-signed honest receipt VERIFIED in both; `
    + `effectDigest=0*64 re-signed: exit 1 REFUSED \`effect-digest-mismatch\` in ${modes.join(' and ')} (and \`--expect `
    + `effect-digest-mismatch\` exits 0 in both) — the code is the DIGEST's refusal, never \`signature-invalid\`, so the VALID `
    + `signature over the mutated body was accepted and the digest was refused; keypair generated in this process, private `
    + `half ${zeroed.privateHalfBytes} bytes and ABSENT from both written files`
})

// ── 4. the dependencies are REQUIRED: a missing one fails by name ──────────────────────────────

arm('a vendored tree WITHOUT the diamond package fails by name (SETUP: cannot import)', broken => {
  const copy = join(work, broken ? 'vendor-whole' : 'vendor-no-diamond')
  cpSync(PACKAGE_ROOT, copy, { recursive: true })
  if (!broken) rmSync(join(copy, 'diamond'), { recursive: true })
  const run = spawnSync('python3', [join(copy, 'scripts/verify-kira-evidence.py'),
    '--record', 'x', '--receipt', 'y', '--log', 'z', '--anchor', 'w', '--package-root', copy],
  { cwd: emptyDir, encoding: 'utf8', env: childEnv })
  assert.equal(run.status, 2, `expected the documented usage/setup exit 2, got ${run.status}`)
  assert.match(run.stderr, /SETUP: cannot import diamond\.kira_evidence/u,
    'a missing package must be reported by name, not as a traceback')
  return `diamond/ removed from a DISPOSABLE copy of vendor/kira-export: exit 2, stderr names the import failure`
})

arm('a vendored tree WITHOUT the consumer script fails naming the missing file', broken => {
  const copy = join(work, broken ? 'vendor-with-script' : 'vendor-no-script')
  cpSync(PACKAGE_ROOT, copy, { recursive: true })
  if (!broken) rmSync(join(copy, 'scripts/verify-kira-evidence.py'))
  const run = spawnSync('python3', [join(copy, 'scripts/verify-kira-evidence.py'), '--help'],
    { cwd: emptyDir, encoding: 'utf8', env: childEnv })
  assert.equal(run.status, 2, `expected exit 2 for a missing consumer, got ${run.status}`)
  assert.match(run.stderr, /verify-kira-evidence\.py/u, 'the failure must name the file that is missing')
  assert.match(run.stderr, /No such file or directory|can't open file/u)
  return `the consumer script removed from a DISPOSABLE copy: exit 2, stderr names verify-kira-evidence.py`
})

// ── 5. the repo's own driver, cold, over the same export ───────────────────────────────────────

arm('scripts/kira/verify-public-evidence.py, run cold, VERIFIES the export', broken => {
  // MUTATION: one byte of the receipt — which the driver first checks against the manifest digest.
  const dir = broken ? copyTree(exportDir, join(work, 'driver-mutated')) : exportDir
  const flipped = broken ? flipOneByte(join(dir, 'evidence/receipts', `${STEM}.json`), '"sig": "') : null
  const run = spawnSync('python3', [DRIVER, '--export', dir, '--package-root', PACKAGE_ROOT, '--json'],
    { cwd: emptyDir, encoding: 'utf8', env: childEnv, timeout: 120_000 })
  assert.equal(run.status, 0, `expected the driver to exit 0 from the empty cwd, got ${run.status}: ${run.stderr}`)
  const report = JSON.parse(run.stdout)
  assert.equal(report.publication, 'VERIFIED')
  assert.equal(report.consumerStatus, 'VERIFIED')
  assert.equal(report.consumerVerified, true)
  assert.equal(report.consumerExitCode, 0)
  // The driver reports WHICH consumer bytes it ran: pinned to the vendored file and to the upstream pin.
  assert.equal(report.consumerSha256, sha256(readFileSync(CONSUMER)))
  assert.equal(report.consumerSha256, 'bd153146c74f7f99721d6b1230dd6aa0dc0a51065192e26a3dbc13310eb088d7',
    'the vendored consumer is not the pinned upstream revision')
  return `driver exit 0 from the empty cwd over ${flipped === null ? 'the intact export' : `a MUTATED export (${flipped})`}; `
    + `consumer sha256 ${report.consumerSha256.slice(0, 16)}… (the vendored file, upstream pin)`
})

// ── verdict ────────────────────────────────────────────────────────────────────────────────────

process.stdout.write(`\n${String(arms)} arm(s); ${MUTATE ? 'each broken once (all must go red)' : 'run the same file with --mutate to require the red half'}\n`)
if (MUTATE) process.stdout.write(`${evidence.map(line => `  ${line}`).join('\n')}\n`)
process.stdout.write(failures === 0
  ? (MUTATE ? '\nALL ARMS PASSED, AND EVERY ARM WENT RED WHEN BROKEN\n' : '\nALL ARMS PASSED\n')
  : `\n${String(failures)} ARM(S) FAILED\n`)

disposeCourtTemps()
process.exitCode = failures === 0 ? 0 : 1
