// SPDX-License-Identifier: AGPL-3.0-or-later
// Focused generic negative controls and durable delivery; no external effects.
import assert from 'node:assert/strict'
import {rm,mkdtemp,realpath} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {operationDigest} from '../../contracts/src/runtime.mjs'
import {OpenShellOwnedExecutor,OwnedLedger} from '../src/index.mjs'
import {fixture,request,settings,MockedProtocolExecutor} from './harness.mjs'
const roots=[]
const make=async(...args)=>{const f=await fixture(...args);roots.push(f.root);return f}
const cases={
  async digest(){const f=await make(),r=request();r.consumed_grant.operation_digest='sha256:'+'b'.repeat(64);await assert.rejects(f.executor.execute(r),e=>e.code==='UNAUTHORIZED');assert.equal(f.broker.read().calls.length,0);assert.equal(f.protocol.calls.length,0);f.ledger.close()},
  async grant(){const f=await make(),r=request();r.consumed_grant.owner_id='changed-owner';await assert.rejects(f.executor.execute(r),e=>e.code==='UNAUTHORIZED');assert.equal(f.broker.read().calls.length,0);f.ledger.close()},
  async expiry(){const f=await make(),r=request();r.operation.expiry=new Date(Date.now()-1000).toISOString();r.consumed_grant.operation_digest=operationDigest(r.operation);await assert.rejects(f.executor.execute(r),e=>e.code==='EXPIRED');assert.equal(f.broker.read().calls.length,0);f.ledger.close()},
  async target(){const f=await make(),r=request();r.operation.target_identity.image_digest='sha256:'+'b'.repeat(64);r.consumed_grant.operation_digest=operationDigest(r.operation);await assert.rejects(f.executor.execute(r),e=>e.code==='TARGET_MISMATCH');assert.equal(f.broker.read().calls.length,0);f.ledger.close()},
  async bounds(){const f=await make(),r=request();r.wall_time_ms=499;await assert.rejects(f.executor.execute(r),e=>e.code==='TARGET_MISMATCH');assert.equal(f.broker.read().calls.length,0);f.ledger.close()},
  async lease(){const f=await make();await f.ledger.withLease(async()=>{await assert.rejects(f.executor.execute(request()),e=>e.code==='RECONCILIATION_REQUIRED')});assert.equal(f.broker.read().calls.length,0);f.ledger.close()},
  async admission(){let f;f=await make({afterCreate(){f.protocol.getSandbox().spec.policy.process.runAsUser='0'}});const receipt=await f.executor.execute(request());assert.equal(receipt.status,'outcome_unknown');assert.equal(f.protocol.calls.filter(([name])=>name==='exec').length,0);f.ledger.close()},
  async qualification(){const f=await make();for(const qualification of [null,()=>true,async()=>true,{record:true,evidence:[],proof:true,verifyAcceptedProof:()=>true}]){const executor=new OpenShellOwnedExecutor({settings,transport:f.transport,ledger:f.ledger,broker:f.broker,qualification});assert.equal(executor.capability,'unavailable');assert.equal(executor.availability().runtimeEnforcementVerified,false);await assert.rejects(executor.execute(request()),e=>e.code==='UNAVAILABLE')}assert.equal(f.broker.read().calls.length,0);assert.equal(f.executor.availability().protocol,'mocked');assert.equal(f.executor.availability().runtimeEnforcementVerified,false);f.ledger.close()},
  async lost_settlement(){const f=await make(),r=request(),original=f.executor.broker.settle;let lost=true;f.executor.broker.settle=async input=>{const reply=original(input);if(lost){lost=false;throw new Error('synthetic lost settlement reply')}return reply};await assert.rejects(f.executor.execute(r),e=>e.code==='RECONCILIATION_REQUIRED'&&e.executionReceipt.status==='completed');assert.equal(f.ledger.pending().length,0);assert.equal(f.ledger.recovery().length,1);f.ledger.close();const ledger=new OwnedLedger(f.root),executor=new MockedProtocolExecutor({settings,transport:f.transport,ledger,broker:f.broker});const receipts=await executor.reconcileOwned();assert.equal(receipts[0].status,'completed');assert.equal(ledger.recovery().length,0);assert.equal(f.broker.read().calls.filter(([name])=>name==='claimDispatch').length,1);assert.equal(f.protocol.calls.filter(([name])=>name==='exec').length,1);assert.equal(ledger.lookup(r.request_id).outbox[0].reply.idempotent,true);ledger.close()},
  async reconcile_delivery(){const f=await make({cleanupFailure:true}),r=request();const first=await f.executor.execute(r);assert.equal(first.status,'outcome_unknown');f.protocol.setCleanup(false);await f.executor.execute(request());const row=f.broker.read().rows[r.operation.operation_id];assert.equal(row.status,'COMPLETED');assert.equal(row.receipt.cleanup,'confirmed_absent');assert.equal(f.broker.read().calls.filter(([name,input])=>name==='reconcileSettlement'&&input.request_id===r.request_id).length,1);f.ledger.close()},
  async lost_ledger(){const f=await make(),r=request();await f.executor.execute(r);f.ledger.close();const root=await realpath(await mkdtemp(join(tmpdir(),'prime-lost-ledger-')));roots.push(root);assert.throws(()=>new OwnedLedger(root),e=>e.code==='RECONCILIATION_REQUIRED');const ledger=new OwnedLedger(root,{initialize:true}),executor=new MockedProtocolExecutor({settings,transport:f.transport,ledger,broker:f.broker});await assert.rejects(executor.execute(r),e=>e.code==='REPLAYED');assert.equal(f.protocol.calls.filter(([name])=>name==='exec').length,1);assert.equal(ledger.lookup(r.request_id).claim_state,'refused');ledger.close()},
  async late_abort(){const controller=new AbortController();let f;f=await make();const del=f.transport.raw.deleteSandbox;f.transport.raw.deleteSandbox=async(...args)=>{controller.abort();return del(...args)};const r=request({signal:controller.signal}),receipt=await f.executor.execute(r);assert.equal(receipt.status,'completed');assert.equal(receipt.exit_code,0);assert.equal(f.broker.read().calls.filter(([name])=>name==='requestCancel').length,0);assert.equal(f.broker.read().rows[r.operation.operation_id].status,'COMPLETED');f.ledger.close()},
  async prelaunch_cancel(){const controller=new AbortController();const f=await make({afterCreate(){controller.abort()}});const r=request({signal:controller.signal}),receipt=await f.executor.execute(r);assert.equal(receipt.status,'cancelled');assert.equal(receipt.started_at,null);assert.equal(receipt.rpc_completion,'not_started');assert.equal(receipt.cleanup,'confirmed_absent');assert.equal(f.broker.read().rows[r.operation.operation_id].status,'CANCELLED');f.ledger.close()},
  async started_abort(){const controller=new AbortController(),f=await make({waitAbort:true}),r=request({signal:controller.signal});const run=f.executor.execute(r);while(!f.protocol.calls.some(([name])=>name==='exec'))await new Promise(resolve=>setImmediate(resolve));controller.abort();const receipt=await run;assert.equal(receipt.status,'outcome_unknown');assert.equal(receipt.rpc_completion,'transport_failed');assert.equal(receipt.cleanup,'confirmed_absent');assert.equal(f.broker.read().rows[r.operation.operation_id].status,'OUTCOME_UNKNOWN');f.ledger.close()}
}
try{for(const [label,run] of Object.entries(cases)){if(process.argv[2]&&process.argv[2]!==label)continue;await run();console.log('PASS '+label)}}finally{for(const root of roots)await rm(root,{recursive:true,force:true})}
