// SPDX-License-Identifier: AGPL-3.0-or-later
// Focused generic negative controls and durable delivery; no external effects.
import assert from 'node:assert/strict'
import {rm,mkdtemp,realpath} from 'node:fs/promises'
import {writeFileSync} from 'node:fs'
import {createHash} from 'node:crypto'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {operationDigest,canonicalJson} from '../../contracts/src/runtime.mjs'
import {OpenShellOwnedExecutor,OwnedLedger,SdkTransport,qualificationRecordDigest,qualificationEvidenceDigest,hostProfileDigest,SDK_SOURCE_COMMIT} from '../src/index.mjs'
import {fixture,request,settings,MockedProtocolExecutor} from './harness.mjs'
const roots=[]
const make=async(...args)=>{const f=await fixture(...args);roots.push(f.root);return f}

function syntheticQualification(f,gateway_identity='https://synthetic.invalid:19443/') {
  const host_profile={host_id:'synthetic-host',os:'linux',architecture:'amd64',kernel_release:'synthetic-kernel',landlock_abi:3,seccomp_notify:true,cgroup_version:2,docker_version:'synthetic-version'}
  const record={version:1,qualification_id:'synthetic-not-owner-accepted',workspace:settings.workspace,logical_workspace_root:settings.logical_workspace_root,image_digest:settings.image_digest,policy_digest:request().policy_digest,sdk_source_commit:SDK_SOURCE_COMMIT,sdk_package_version:'0.0.0',host_profile,gateway_identity,ledger_id:f.ledger.identity,bounds:{cpu_millicores:500,memory_bytes:536870912,scratch_bytes:134217728,pids:64,wall_time_ms:500,max_output_bytes:128},evidence_digest:null,accepted_at:new Date(Date.now()-1000).toISOString(),expires_at:new Date(Date.now()+60000).toISOString()}
  const {version,qualification_id,evidence_digest,accepted_at,expires_at,...scope}=record
  const sd='sha256:'+createHash('sha256').update('aukora-prime.runtime-scope.v1\0'+canonicalJson(scope)).digest('hex')
  const evidence=['image_pin','sdk_pin','policy_admission','host_profile','identity_isolation','private_control_credentials','no_host_mounts','network_denial','cpu_bound','memory_bound','scratch_bound','pid_bound','timeout_cleanup','restart_reconciliation','scoped_cleanup'].map(check=>({check,artifact_digest:'sha256:'+'c'.repeat(64),observed_at:record.accepted_at,scope_digest:sd,status:'passed'}))
  record.evidence_digest=qualificationEvidenceDigest(evidence)
  const proof={kind:'host_runtime_acceptance',record_digest:qualificationRecordDigest(record),evidence_digest:record.evidence_digest,host_profile_digest:hostProfileDigest(host_profile),accepted_by:'synthetic-host-only',material:{fixture:'never-real-owner-acceptance'}}
  const qualification={record,evidence,proof,verifyAcceptedProof:()=>true}
  const runtimeBinding={host_profile_digest:proof.host_profile_digest,gateway_identity:record.gateway_identity,ledger_id:record.ledger_id}
  return {qualification,runtimeBinding,transport:new SdkTransport(f.protocol.raw,{gatewayIdentity:record.gateway_identity})}
}

const cases={
  async digest(){const f=await make(),r=request();r.consumed_grant.operation_digest='sha256:'+'b'.repeat(64);await assert.rejects(f.executor.execute(r),e=>e.code==='UNAUTHORIZED');assert.equal(f.broker.read().calls.length,0);assert.equal(f.protocol.calls.length,0);f.ledger.close()},
  async grant(){const f=await make(),r=request();r.consumed_grant.owner_id='changed-owner';await assert.rejects(f.executor.execute(r),e=>e.code==='UNAUTHORIZED');assert.equal(f.broker.read().calls.length,0);f.ledger.close()},
  async expiry(){const f=await make(),r=request();r.operation.expiry=new Date(Date.now()-1000).toISOString();r.consumed_grant.operation_digest=operationDigest(r.operation);await assert.rejects(f.executor.execute(r),e=>e.code==='EXPIRED');assert.equal(f.broker.read().calls.length,0);f.ledger.close()},
  async target(){const f=await make(),r=request();r.operation.target_identity.image_digest='sha256:'+'b'.repeat(64);r.consumed_grant.operation_digest=operationDigest(r.operation);await assert.rejects(f.executor.execute(r),e=>e.code==='TARGET_MISMATCH');assert.equal(f.broker.read().calls.length,0);f.ledger.close()},
  async bounds(){const f=await make(),r=request();r.wall_time_ms=499;await assert.rejects(f.executor.execute(r),e=>e.code==='TARGET_MISMATCH');assert.equal(f.broker.read().calls.length,0);f.ledger.close()},
  async lease(){const f=await make(),other=new OwnedLedger(f.root),executor=new MockedProtocolExecutor({settings,transport:f.transport,ledger:other,broker:f.broker});await f.ledger.withLease(async()=>{await assert.rejects(executor.execute(request()),e=>e.code==='RECONCILIATION_REQUIRED')});assert.equal(f.broker.read().calls.length,0);other.close();f.ledger.close()},
  async expiry_after_claim(){const f=await make({}, {beforeClaim:async()=>{await new Promise(resolve=>setTimeout(resolve,80));return true}}),r=request();r.operation.expiry=new Date(Date.now()+40).toISOString();r.consumed_grant.operation_digest=operationDigest(r.operation);const receipt=await f.executor.execute(r);assert.equal(receipt.status,'outcome_unknown');assert.equal(f.protocol.calls.filter(([name])=>name==='create').length,0);f.ledger.close()},
  async admission(){let f;f=await make({afterCreate(){f.protocol.getSandbox().spec.policy.process.runAsUser='0'}});const receipt=await f.executor.execute(request());assert.equal(receipt.status,'outcome_unknown');assert.equal(f.protocol.calls.filter(([name])=>name==='exec').length,0);f.ledger.close()},
  async qualification(){const f=await make();for(const qualification of [null,()=>true,async()=>true,{record:true,evidence:[],proof:true,verifyAcceptedProof:()=>true}]){const executor=new OpenShellOwnedExecutor({settings,transport:f.transport,ledger:f.ledger,broker:f.broker,qualification});assert.equal(executor.capability,'unavailable');assert.equal(executor.availability().runtimeEnforcementVerified,false);await assert.rejects(executor.execute(request()),e=>e.code==='UNAVAILABLE')}assert.equal(f.broker.read().calls.length,0);assert.equal(f.executor.availability().protocol,'mocked');assert.equal(f.executor.availability().runtimeEnforcementVerified,false);f.ledger.close()},
  async accepted_proof(){const f=await make(),q=syntheticQualification(f);let verified=0;q.qualification.verifyAcceptedProof=()=>{verified++;return true};const e=new OpenShellOwnedExecutor({settings,ledger:f.ledger,broker:f.broker,...q});assert.equal(e.capability,'unavailable');assert.equal(e.availability().runtimeEnforcementVerified,false);assert(verified>0);const accept=v=>({status:'ACCEPTED',record_digest:v.proof.record_digest,evidence_digest:v.proof.evidence_digest,host_profile_digest:v.proof.host_profile_digest,accepted_by:v.proof.accepted_by});q.qualification.verifyAcceptedProof=accept;for(const binding of [{...q.runtimeBinding,gateway_identity:'https://other.invalid/'},{...q.runtimeBinding,host_profile_digest:'sha256:'+'d'.repeat(64)},{...q.runtimeBinding,ledger_id:'different-ledger'}]){const changed=new OpenShellOwnedExecutor({settings,ledger:f.ledger,broker:f.broker,...q,runtimeBinding:binding});assert.equal(changed.capability,'unavailable');assert.equal(changed.availability().runtimeEnforcementVerified,false)}for(const identity of [null,'','http://synthetic.invalid/']){const invalid=syntheticQualification(f,identity);invalid.qualification.verifyAcceptedProof=accept;const changed=new OpenShellOwnedExecutor({settings,ledger:f.ledger,broker:f.broker,...invalid});assert.equal(changed.capability,'unavailable')}assert.equal(f.broker.read().calls.length,0);f.ledger.close()},
  async gateway_recovery(){const f=await make({cleanupFailure:true}),r=request();await f.executor.execute(r);f.protocol.setCleanup(false);const transport=new SdkTransport(f.protocol.raw,{gatewayIdentity:'https://different.invalid:19443/'}),executor=new MockedProtocolExecutor({settings,transport,ledger:f.ledger,broker:f.broker}),before=f.protocol.calls.length;const receipts=await executor.reconcileOwned();assert.equal(receipts[0].status,'outcome_unknown');assert.equal(receipts[0].cleanup,'unknown');assert.equal(receipts[0].reconciliation_required,true);assert.equal(f.protocol.calls.length,before);assert.equal(f.protocol.calls.filter(([name])=>name==='delete').length,0);f.ledger.close()},
  async damaged_ledger(){const f=await make();f.ledger.close();writeFileSync(join(f.root,'jobs.sqlite'),Buffer.alloc(0));assert.throws(()=>new OwnedLedger(f.root),e=>e.code==='RECONCILIATION_REQUIRED');assert.throws(()=>new OwnedLedger(f.root,{initialize:true}),e=>e.code==='RECONCILIATION_REQUIRED')},
  async uncertainty_fence(){const f=await make({trailerFailure:true}),r=request();const receipt=await f.executor.execute(r);assert.equal(receipt.status,'outcome_unknown');assert.equal(receipt.cleanup,'confirmed_absent');assert.equal(receipt.reconciliation_required,true);await assert.rejects(f.executor.execute(request()),e=>e.code==='RECONCILIATION_REQUIRED');assert.equal(f.protocol.calls.filter(([name])=>name==='exec').length,1);f.ledger.close()},
  async lost_settlement(){const f=await make(),r=request(),original=f.executor.broker.settle;let lost=true;f.executor.broker.settle=async input=>{const reply=original(input);if(lost){lost=false;throw new Error('synthetic lost settlement reply')}return reply};await assert.rejects(f.executor.execute(r),e=>e.code==='RECONCILIATION_REQUIRED'&&e.executionReceipt.status==='completed');assert.equal(f.ledger.pending().length,0);assert.equal(f.ledger.recovery().length,1);f.ledger.close();const ledger=new OwnedLedger(f.root),executor=new MockedProtocolExecutor({settings,transport:f.transport,ledger,broker:f.broker});const receipts=await executor.reconcileOwned();assert.equal(receipts[0].status,'completed');assert.equal(ledger.recovery().length,0);assert.equal(f.broker.read().calls.filter(([name])=>name==='claimDispatch').length,1);assert.equal(f.protocol.calls.filter(([name])=>name==='exec').length,1);assert.equal(ledger.lookup(r.request_id).outbox[0].reply.idempotent,true);ledger.close()},
  async reconcile_delivery(){const f=await make({cleanupFailure:true}),r=request();const first=await f.executor.execute(r);assert.equal(first.status,'outcome_unknown');f.protocol.setCleanup(false);await f.executor.execute(request());const row=f.broker.read().rows[r.operation.operation_id];assert.equal(row.status,'COMPLETED');assert.equal(row.receipt.cleanup,'confirmed_absent');assert.equal(f.broker.read().calls.filter(([name,input])=>name==='reconcileSettlement'&&input.request_id===r.request_id).length,1);f.ledger.close()},
  async lost_ledger(){const f=await make(),r=request();await f.executor.execute(r);f.ledger.close();const root=await realpath(await mkdtemp(join(tmpdir(),'prime-lost-ledger-')));roots.push(root);assert.throws(()=>new OwnedLedger(root),e=>e.code==='RECONCILIATION_REQUIRED');const ledger=new OwnedLedger(root,{initialize:true}),executor=new MockedProtocolExecutor({settings,transport:f.transport,ledger,broker:f.broker});await assert.rejects(executor.execute(r),e=>e.code==='REPLAYED');assert.equal(f.protocol.calls.filter(([name])=>name==='exec').length,1);assert.equal(ledger.lookup(r.request_id).claim_state,'refused');ledger.close()},
  async late_abort(){const controller=new AbortController();let f;f=await make();const del=f.transport.raw.deleteSandbox;f.transport.raw.deleteSandbox=async(...args)=>{controller.abort();return del(...args)};const r=request({signal:controller.signal}),receipt=await f.executor.execute(r);assert.equal(receipt.status,'completed');assert.equal(receipt.exit_code,0);assert.equal(f.broker.read().calls.filter(([name])=>name==='requestCancel').length,0);assert.equal(f.broker.read().rows[r.operation.operation_id].status,'COMPLETED');f.ledger.close()},
  async prelaunch_cancel(){const controller=new AbortController();const f=await make({afterCreate(){controller.abort()}});const r=request({signal:controller.signal}),receipt=await f.executor.execute(r);assert.equal(receipt.status,'cancelled');assert.equal(receipt.started_at,null);assert.equal(receipt.rpc_completion,'not_started');assert.equal(receipt.cleanup,'confirmed_absent');assert.equal(f.broker.read().rows[r.operation.operation_id].status,'CANCELLED');f.ledger.close()},
  async started_abort(){const controller=new AbortController(),f=await make({waitAbort:true}),r=request({signal:controller.signal});const run=f.executor.execute(r);while(!f.protocol.calls.some(([name])=>name==='exec'))await new Promise(resolve=>setImmediate(resolve));controller.abort();const receipt=await run;assert.equal(receipt.status,'outcome_unknown');assert.equal(receipt.rpc_completion,'transport_failed');assert.equal(receipt.cleanup,'confirmed_absent');assert.equal(f.broker.read().rows[r.operation.operation_id].status,'OUTCOME_UNKNOWN');f.ledger.close()}
}
try{for(const [label,run] of Object.entries(cases)){if(process.argv[2]&&process.argv[2]!==label)continue;await run();console.log('PASS '+label)}}finally{for(const root of roots)await rm(root,{recursive:true,force:true})}
