export interface MemoryCapture {readonly statement:string;readonly attributed_to:string}
export interface Presentation { readonly operation: Readonly<Record<string,unknown>>; readonly operation_digest:string; readonly approval_expiry:string; readonly canonical_operation:string; readonly review_challenge:Readonly<Record<string,unknown>>; readonly rows: readonly {key:string;label:string;exact:string}[]; readonly memory_review:(MemoryCapture & {readonly capture_sha256:string})|null }
export interface Capabilities {readonly version:1;readonly source_commit:string;readonly runtime_pid:number;readonly release_digest:string;readonly unavailable_capabilities:readonly string[];readonly phase:'disposable-preview';readonly qualification:'PENDING'}
export interface OwnerState {readonly phase:string;readonly owner:{owner_id:string;expiry:string}|null;readonly owner_id:string;readonly presentation:Presentation|null;readonly operation_available:boolean;readonly login_kinds:readonly string[];readonly fixture:boolean;readonly expired:boolean;readonly reason:string;readonly error_code:string|null;readonly capabilities:Capabilities|null;readonly capability_status:string;readonly authority_available:boolean}
export interface Binding {authority:Record<string,(input:unknown,options?:{signal?:AbortSignal})=>Promise<unknown>>; contracts:{validateContract(name:string,value:unknown):unknown;validateApprovalTemplate?(value:unknown):unknown;parseStrictJson?(text:string,options?:{maxBytes?:number;maxDepth?:number}):unknown;canonicalJson(value:unknown):string;operationDigest(value:unknown):string|Promise<string>};owner_id?:string;loginKinds?:readonly string[];approvalKind?:string;fixture?:boolean;requiresCapabilities?:boolean;passkeyProfile?:{profile:'https'|'localhost-pilot-v1';origin:string;rp_id:string};ownerSigner?:(input:unknown)=>Promise<unknown>;passkeySigner?:(input:unknown)=>Promise<unknown>;operation?:unknown;memoryCapture?:MemoryCapture}
export interface Controller {getSnapshot():OwnerState;subscribe(listener:()=>void):()=>void;connect(binding:Binding):void;setCapabilities(value:unknown):void;capabilitiesUnavailable():void;setOwnerId(owner_id:string):void;setOperation(proposal:unknown,options?:{memoryCapture?:MemoryCapture}):void;login(kind?:string):Promise<unknown>;prepare():Promise<unknown>;approve():Promise<unknown>;decline():Promise<unknown>;logout():void;disconnect():void;dispose():void}
export function createPrimeOwnerController(options?:{now?:()=>number;schedule?:typeof setTimeout;unschedule?:typeof clearTimeout}):Controller
export function createHttpAuthority(fetcher?:typeof fetch,contracts?:Binding['contracts']):Binding['authority']
export function readHttpCapabilities(fetcher?:typeof fetch,contracts?:Binding['contracts'],signal?:AbortSignal):Promise<Capabilities>
export function validateCapabilities(value:unknown):Capabilities
export const CAPABILITY_LABELS:Readonly<Record<string,string>>
