import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useSyncExternalStore } from 'react';
import { ActionButton, Panel, SectionHeader } from '@aukora/face-layout/client';
import { CAPABILITY_LABELS } from './controller.mjs';
import { validateCaptureReview } from '../../../adapters/capture-review.mjs';
import css from './OwnerSurface.module.css';
export function OwnerSurface({ activeSurface, controller }) {
    const state = useSyncExternalStore(controller.subscribe, controller.getSnapshot, controller.getSnapshot);
    const busy = state.phase.endsWith('_pending') || state.approval_action_pending;
    const locked = busy || state.phase === 'outcome_unknown';
    const view = state.presentation;
    let memoryReady = view?.operation.action_type !== 'memory.save';
    if (!memoryReady && view?.memory_review) {
        try {
            validateCaptureReview(view.operation.canonical_parameters, {
                statement: view.memory_review.statement, attributed_to: view.memory_review.attributed_to,
            });
            memoryReady = view.memory_review.capture_sha256 === view.operation.canonical_parameters.capture_sha256;
        }
        catch { /* Missing or changed memory content must remain unapprovable. */ }
    }
    return _jsxs("section", { className: css.surface, hidden: activeSurface !== 'prime-owner', "data-prime-owner-surface": true, "data-phase": state.phase, children: [_jsxs(SectionHeader, { className: css.header, children: [_jsx("h1", { children: "Owner access and approvals" }), _jsx("p", { children: "Use an existing credential. Enrollment is unavailable here." })] }), state.fixture && _jsx("p", { role: "alert", "data-disposable-fixture": true, children: "Disposable UI fixture. Authentication and approvals below are synthetic; no effect is executed." }), _jsx(Panel, { className: css.card, children: _jsx(CapabilityDetails, { controller: controller }) }), _jsxs(Panel, { className: css.card, children: [_jsx("h2", { children: "Owner session" }), state.owner ? _jsxs(_Fragment, { children: [_jsxs("p", { "data-owner-confirmed": true, children: ["Host-confirmed owner: ", _jsx("code", { children: state.owner.owner_id })] }), _jsxs("p", { children: ["Session expires: ", _jsx("time", { children: state.owner.expiry })] })] })
                        : _jsxs("label", { className: css.owner, children: ["Owner ID", _jsx("input", { autoComplete: "off", value: state.owner_id, disabled: busy, onChange: event => controller.setOwnerId(event.target.value), "aria-label": "Owner ID" })] }), _jsxs("div", { className: css.actions, children: [!state.owner && state.login_kinds.map(kind => _jsx(ActionButton, { disabled: busy || !state.owner_id || !state.authority_available || state.phase === 'unavailable', onClick: () => { void controller.login(kind); }, children: kind === 'passkey' ? 'Sign in with passkey' : 'Sign in with owner key' }, kind)), state.owner && _jsx(ActionButton, { disabled: busy, onClick: () => controller.logout(), children: "Sign out" })] })] }), _jsxs(Panel, { className: css.card, children: [_jsx("h2", { children: "Exact operation" }), !state.operation_available && _jsx("p", { children: "No operation has been supplied by the host." }), state.operation_available && _jsx(ActionButton, { disabled: !state.owner || locked || !state.authority_available || state.phase === 'approved' || state.phase === 'denied', onClick: () => { void controller.prepare(); }, children: "Request fresh review" }), view && _jsxs(_Fragment, { children: [view.operation.action_type === 'memory.save' && _jsxs("div", { "data-memory-capture-review": true, children: [_jsx("h3", { children: "Exact memory statement" }), memoryReady ? _jsxs(_Fragment, { children: [_jsx("pre", { "data-memory-statement": true, children: view.memory_review.statement }), _jsx("p", { children: "Attribution" }), _jsx("pre", { "data-memory-attribution": true, children: view.memory_review.attributed_to }), _jsx("p", { children: "Capture hash" }), _jsx("pre", { "data-memory-capture-hash": true, children: view.memory_review.capture_sha256 }), _jsx("p", { children: "The operation digest below binds this exact statement and attribution. The host verifies the private capture." })] })
                                        : _jsx("p", { role: "alert", "data-memory-review-refused": true, children: "The exact memory statement and attribution are missing or do not match the capture draft. Approval is unavailable." })] }), _jsx("dl", { className: css.fields, "data-exact-operation": true, children: view.rows.map(row => _jsxs("div", { "data-operation-field": row.key, children: [_jsxs("dt", { children: [row.label, " ", _jsxs("code", { children: ["(", row.key, ")"] })] }), _jsx("dd", { children: _jsx("pre", { children: row.exact }) })] }, row.key)) }), _jsx("p", { children: "Operation digest" }), _jsx("pre", { "data-operation-digest": true, children: view.operation_digest }), _jsxs("p", { children: ["Review expires: ", _jsx("time", { "data-approval-expiry": true, children: view.approval_expiry })] }), _jsx("p", { children: "Fresh review challenge" }), _jsx("pre", { "data-review-challenge": true, children: JSON.stringify(view.review_challenge, null, 2) }), _jsx("p", { children: "Exact canonical operation" }), _jsx("pre", { "data-canonical-operation": true, children: view.canonical_operation }), _jsxs("div", { className: css.actions, children: [_jsx(ActionButton, { variant: "gold", disabled: state.phase !== 'review_ready' || state.expired || !state.authority_available || !memoryReady || busy ||
                                            (view.operation.action_type === 'memory.save' && !state.approval_action_available), onClick: () => { void controller.submitApproval(); }, children: "Approve exact operation" }), _jsx(ActionButton, { variant: "red-warning", disabled: state.phase !== 'review_ready' || state.expired || !state.authority_available, onClick: () => { void controller.decline(); }, children: "Decline" })] }), view.operation.action_type === 'memory.save' && !state.approval_action_available && !state.approval_action_result &&
                                _jsx("p", { role: "status", "data-memory-action-unavailable": true, children: "The memory approval workflow is unavailable." })] })] }), state.approval_action_result && _jsxs(Panel, { className: css.card, "data-memory-workflow-result": true, children: [_jsx("h2", { children: "Host memory workflow result" }), _jsxs("dl", { className: css.fields, children: [_jsxs("div", { children: [_jsx("dt", { children: "Approval" }), _jsx("dd", { "data-memory-approval-status": true, children: state.approval_action_result.approval })] }), _jsxs("div", { children: [_jsx("dt", { children: "Save" }), _jsx("dd", { "data-memory-save-status": true, children: state.approval_action_result.save })] }), _jsxs("div", { children: [_jsx("dt", { children: "Index" }), _jsx("dd", { "data-memory-index-status": true, children: state.approval_action_result.index.status })] }), _jsxs("div", { children: [_jsx("dt", { children: "Citation" }), _jsx("dd", { "data-memory-citation-status": true, children: state.approval_action_result.citation_status })] }), _jsxs("div", { children: [_jsx("dt", { children: "Authority settlement" }), _jsx("dd", { "data-memory-settlement-status": true, children: state.approval_action_result.authority_settlement ?? 'unconfirmed' })] }), _jsxs("div", { children: [_jsx("dt", { children: "Receipt digest" }), _jsx("dd", { children: _jsx("pre", { "data-memory-receipt-digest": true, children: state.approval_action_result.receipt_digest ?? 'unconfirmed' }) })] })] }), state.approval_action_result.reconciliation_required && _jsx("p", { role: "alert", children: "Reconciliation is required. Do not retry this save." }), state.approval_action_result.read_error_code && _jsxs("p", { role: "status", children: ["Index or citation read unavailable: ", state.approval_action_result.read_error_code] }), state.approval_action_result.receipt && _jsxs("details", { children: [_jsx("summary", { children: "Exact host receipt" }), _jsx("pre", { "data-memory-effect-receipt": true, children: JSON.stringify(state.approval_action_result.receipt, null, 2) })] }), state.approval_action_result.citation && _jsxs("details", { children: [_jsx("summary", { children: "Exact citation" }), _jsx("pre", { "data-memory-citation": true, children: JSON.stringify(state.approval_action_result.citation, null, 2) })] })] }), _jsx("p", { role: "status", "aria-live": "polite", "data-prime-authority-status": true, children: state.reason }), state.error_code && _jsx("p", { role: "alert", className: css.error, "data-authority-error": state.error_code, children: state.error_code }), state.expired && _jsx("p", { role: "alert", children: "This session or review has expired." })] });
}
function CapabilityDetails({ controller }) {
    const state = useSyncExternalStore(controller.subscribe, controller.getSnapshot, controller.getSnapshot);
    const value = state.capabilities;
    return _jsxs("div", { "data-prime-capability-status": state.capability_status, children: [_jsx("h2", { children: "Disposable preview \u00B7 qualification pending" }), _jsx("p", { children: "Source metadata does not prove that memory is loaded or a capability is working." }), !value && _jsx("p", { children: state.fixture ? 'Synthetic fixture only. Runtime capability status is unavailable.'
                    : state.capability_status === 'pending' ? 'Waiting for runtime capability status.' : 'Runtime capability status is unavailable.' }), value && _jsxs("dl", { className: css.fields, children: [_jsxs("div", { children: [_jsx("dt", { children: "Source commit" }), _jsx("dd", { children: _jsx("code", { "data-source-commit": true, children: value.source_commit }) })] }), _jsxs("div", { children: [_jsx("dt", { children: "Runtime PID" }), _jsx("dd", { "data-runtime-pid": true, children: value.runtime_pid })] }), _jsxs("div", { children: [_jsx("dt", { children: "Release digest" }), _jsx("dd", { children: _jsx("code", { "data-release-digest": true, children: value.release_digest }) })] })] }), _jsx("ul", { className: css.capabilities, children: Object.entries(CAPABILITY_LABELS).map(([id, label]) => _jsxs("li", { "data-capability": id, children: [label, ": ", _jsx("strong", { children: value?.unavailable_capabilities.includes(id) ? 'Unavailable' : 'Not qualified' })] }, id)) })] });
}
export function CapabilityBadge({ controller }) {
    return _jsxs("details", { className: css.badge, "data-prime-capability-badge": true, "data-reserves-hot-corners": true, children: [_jsx("summary", { children: "Disposable preview \u00B7 pending" }), _jsx("div", { className: css.badgePanel, children: _jsx(CapabilityDetails, { controller: controller }) })] });
}
export function OwnerMenu({ activeSurface, openSurface }) {
    return _jsx(ActionButton, { className: css.menu, "aria-current": activeSurface === 'prime-owner' ? 'page' : undefined, "data-prime-owner-launcher": true, onClick: () => openSurface('prime-owner', undefined, 'contained'), children: "Owner access" });
}
//# sourceMappingURL=OwnerSurface.js.map